# -*- coding: utf-8 -*-
"""Rewrite app_ar.arb with natural Modern Standard Arabic UI strings."""
from __future__ import annotations

import json
import re
import sys
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EN_ARB = ROOT / "lib" / "l10n" / "app_en.arb"
AR_ARB = ROOT / "lib" / "l10n" / "app_ar.arb"
EN_KEYS_JSON = Path(__file__).resolve().parent / "_en_keys.json"

AR = {
    "appTitle": "BarQody",
    "tools": "الأدوات",
    "accountSettings": "إعدادات الحساب",
    "notifications": "الإشعارات",
    "forYou": "لك",
    "yourProfile": "ملفك الشخصي",
    "editProfile": "تعديل الملف الشخصي",
    "editProfileSubtitle": "تغيير الاسم والصورة والنبذة",
    "username": "اسم المستخدم",
    "setUsernameSubtitle": "تعيين اسم مستخدم فريد لملفك",
    "socialLinks": "روابط التواصل",
    "socialLinksSubtitle": "إضافة Instagram وWhatsApp والموقع والمزيد",
    "publicProfile": "الملف العام",
    "publicProfileOn": "يمكن لأي شخص العثور على ملفك وعرضه",
    "publicProfileOff": "مخفي عن البحث — لا يمكن للآخرين اكتشافك",
    "shareQr": "مشاركة رمز QR الخاص بي",
    "shareQrSubtitle": "دع الآخرين يمسحون بطاقة أعمالك الرقمية",
    "shoppingRewards": "التسوق والمكافآت",
    "myOrders": "طلباتي",
    "myOrdersSubtitle": "متابعة الطلبات من المتاجر",
    "myRewardCards": "بطاقات المكافآت",
    "myRewardCardsSubtitle": "عرض الطوابع والنقاط من برامج الولاء",
    "workplace": "مكان العمل",
    "employeeInvitations": "دعوات الموظفين",
    "employeeInvitationsSubtitle": "قبول أو رفض دعوات الفريق من الشركات",
    "workplaceCheckIn": "تسجيل الحضور في العمل",
    "workplaceCheckInSubtitle": "تسجيل الحضور والانصراف في العمل مع الموقع",
    "accountsAndDevices": "الحسابات والأجهزة",
    "linkedDevices": "الأجهزة المرتبطة",
    "linkedDevicesSubtitle": "ربط هاتف آخر مثل WhatsApp",
    "accounts": "الحسابات",
    "accountsSubtitle": "إضافة حسابات أو التبديل بينها",
    "accountsSwitchSubtitle": "التبديل بين {count} من الحسابات",
    "helpAndAccount": "المساعدة والحساب",
    "appLanguage": "لغة التطبيق",
    "appLanguageSubtitle": "تغيير لغة التطبيق",
    "searchLanguage": "بحث عن لغة",
    "phoneLanguage": "لغة الهاتف",
    "languageUpdated": "تم تحديث اللغة",
    "helpFaqs": "المساعدة والأسئلة الشائعة",
    "helpFaqsSubtitle": "إجابات على الأسئلة الشائعة",
    "sendFeedback": "إرسال ملاحظات",
    "sendFeedbackSubtitle": "الإبلاغ عن خطأ أو اقتراح ميزة",
    "logOut": "تسجيل الخروج",
    "logOutSubtitle": "إنهاء هذه الجلسة",
    "cancel": "إلغاء",
    "save": "حفظ",
    "done": "تم",
    "str": "بطاقة الأعمال الرقمية",
    "readOnly": "(للقراءة فقط)",
    "n1Point100PKRExampleRule": "1 نقطة = 100 ر.ب (قاعدة مثال)",
    "n10StampsRequired": "مطلوب 10 طوابع",
    "n123MainStCity": "123 الشارع الرئيسي، المدينة",
    "n2DaysAgo": "منذ يومين",
    "n330CharactersLettersNumbersUnderscoresAndHyphensOnly": "من 3 إلى 30 حرفًا. الأحرف والأرقام والشرطة السفلية والواصلة فقط.",
    "aabbccdd": "AABBCCDD",
    "accept": "قبول",
    "accessRESTRICTED": "الوصول مقيد",
    "accountIBANAddAccountNumberHere": "الحساب / IBAN: أضف رقم الحساب هنا",
    "accountTitleTapni": "اسم الحساب: Tapni",
    "active": "نشط",
    "active2": "نشط",
    "activeCARD": "بطاقة نشطة",
    "add": "إضافة",
    "addANote": "إضافة ملاحظة...",
    "addAccount": "إضافة حساب",
    "addAtLeastOneCategoryFirst": "أضف فئة واحدة على الأقل أولًا",
    "addCategoriesInDisplayOrderEGFastFoodThenDesi": "أضف الفئات حسب ترتيب العرض (مثل: وجبات سريعة، ثم ديسي)",
    "addCategoriesInYourCatalogSettingsFirst": "أضف الفئات من إعدادات الكتالوج أولًا.",
    "addContact": "إضافة جهة اتصال",
    "addLink": "إضافة رابط",
    "addLinksToYourProfileBelow": "أضف الروابط إلى ملفك أدناه",
    "addLinksToYourProfileFirstThenEnableThemHere": "أضف الروابط إلى ملفك أولًا، ثم فعّلها هنا.",
    "addLogo": "إضافة شعار",
    "addPoints": "إضافة نقاط",
    "addProgram": "إضافة برنامج",
    "addStamp": "إضافة طابع",
    "addToGoogleWallet": "إضافة إلى Google Wallet",
    "address": "العنوان",
    "ai": "AI",
    "all": "الكل",
    "allCaughtUp": "لا جديد!",
    "allNotificationsMarkedAsRead": "تم تعليم كل الإشعارات كمقروءة!",
    "allowCamera": "السماح بالكاميرا",
    "allowThisDeviceToAccessYourBarqodyAccountYouCanRemoveItAnytimeFromLinkedDevices": "السماح لهذا الجهاز بالوصول إلى حساب Barqody؟ يمكنك إزالته في أي وقت من الأجهزة المرتبطة.",
    "alreadyHaveAnAccount": "لديك حساب بالفعل؟",
    "analyticsDashboard": "لوحة التحليلات",
    "anySpecialRequests": "أي طلبات خاصة...",
    "apply": "تطبيق",
    "applyDesign": "تطبيق التصميم",
    "applyTemplate": "تطبيق القالب",
    "ascending": "تصاعدي",
    "askYourBusinessToScanYourQRAndAddYouAsAnEmployee": "اطلب من شركتك مسح رمز QR وإضافتك كموظف",
    "assignCategory": "تعيين فئة",
    "assignedPrograms": "البرامج المعيَّنة",
    "atLeast6Characters": "6 أحرف على الأقل",
    "attendanceCompletedForToday": "اكتمل الحضور لهذا اليوم",
    "availableSlots": "الأوقات المتاحة",
    "background": "الخلفية",
    "backgroundColor": "لون الخلفية",
    "bankAccount": "الحساب البنكي",
    "bankDetails": "بيانات البنك",
    "bankAddBankNameHere": "البنك: أضف اسم البنك هنا",
    "barqody": "Barqody",
    "barqodyV100": "Barqody",
    "bestValue": "أفضل قيمة",
    "billAmount": "مبلغ الفاتورة",
    "bio": "نبذة",
    "bio2": "نبذة",
    "book": "حجز",
    "bookingDate": "تاريخ الحجز",
    "bookingSchedule": "جدول الحجز",
    "bookingTime": "وقت الحجز",
    "business": "أعمال",
    "businessCategory": "فئة النشاط",
    "businessDetails": "بيانات النشاط",
    "businessName": "اسم النشاط",
    "businessOptions": "خيارات النشاط",
    "businessPrograms": "برامج النشاط",
    "businessUsersOnly": "لمستخدمي الأعمال فقط",
    "bySigningUpYouAgreeToOurTermsAndConditions": "بإنشاء حساب، فإنك توافق على الشروط والأحكام.",
    "call": "اتصال",
    "cameraPermissionIsRequiredToScan": "إذن الكاميرا مطلوب للمسح.",
    "cancelAnytime": "يمكنك الإلغاء في أي وقت.",
    "cancelOrder": "إلغاء الطلب",
    "captureNewContact": "التقاط جهة اتصال جديدة",
    "categories": "الفئات",
    "category": "الفئة *",
    "categoryAlreadyExists": "الفئة موجودة بالفعل",
    "categoryName": "اسم الفئة",
    "checkIn": "تسجيل حضور",
    "checkOut": "تسجيل انصراف",
    "chooseAUniqueUsernameForYourProfileLink": "اختر اسم مستخدم فريدًا لرابط ملفك.",
    "choosePlan": "اختيار الباقة",
    "chooseTemplate": "اختيار قالب",
    "close": "إغلاق",
    "codeCopied": "تم نسخ الرمز",
    "commingSoon": "قريبًا",
    "company": "الشركة",
    "companyEmployeeCard": "بطاقة موظف الشركة",
    "companyInc": "Company Inc.",
    "completeTheseSteps": "أكمل هذه الخطوات",
    "confirmAddPoints": "تأكيد وإضافة النقاط",
    "confirmBooking": "تأكيد الحجز",
    "confirmLocation": "تأكيد الموقع",
    "confirmRedemption": "تأكيد الاستبدال",
    "connectedAccounts": "الحسابات المتصلة",
    "contactAddedSuccessfully": "تمت إضافة جهة الاتصال بنجاح!",
    "contactCard": "بطاقة جهة الاتصال",
    "contactExchangedSuccessfully": "تم تبادل جهة الاتصال بنجاح!",
    "contactSource": "مصدر جهة الاتصال",
    "contactUpdatedSuccessfully": "تم تحديث جهة الاتصال بنجاح!",
    "contacts": "جهات الاتصال",
    "continueLabel": "متابعة",
    "copied": "تم النسخ",
    "copyCode": "نسخ الرمز",
    "couldNotGetLocationPleaseEnableGPSPermission": "تعذّر الحصول على الموقع. يرجى تفعيل إذن GPS.",
    "couldNotSwitchAccount": "تعذّر التبديل بين الحسابات",
    "create": "إنشاء",
    "createAccount": "إنشاء حساب",
    "createLoyaltyProgram": "إنشاء برنامج ولاء",
    "createNewLink": "إنشاء رابط جديد",
    "createProgram": "إنشاء برنامج",
    "createReward": "إنشاء مكافأة",
    "createStampOrPointsRewardsForCustomers": "إنشاء مكافآت بالطوابع أو النقاط للعملاء",
    "createYourFirstCard": "أنشئ بطاقتك الأولى",
    "createYourFirstRewardCardForCustomers": "أنشئ أول بطاقة مكافآت لعملائك",
    "creationDate": "تاريخ الإنشاء",
    "customImagesForStampedAndUnstampedSlotsDefaultsAreUsedIfNotSet": "صور مخصصة للخانات المختومة وغير المختومة. تُستخدم الافتراضية إن لم تُعيَّن.",
    "customLink": "رابط مخصص",
    "customerDetails": "بيانات العميل",
    "customerEnrolledSuccessfully": "تم تسجيل العميل بنجاح",
    "customerIsNotEnrolledYet": "العميل غير مسجّل بعد",
    "customerNoShow": "عدم حضور العميل",
    "customerOrders": "طلبات العملاء",
    "customizeCardDesign": "تخصيص تصميم البطاقة",
    "customizeDesign": "تخصيص التصميم",
    "customizeYourProfileUnlockPROTemplatesAndGetUnlimitedLeads": "خصّص ملفك، وافتح قوالب PRO، واحصل على عملاء محتملين بلا حد.",
    "customizeYourself": "خصّص بنفسك",
    "date": "التاريخ",
    "dateRange": "نطاق التاريخ",
    "decline": "رفض",
    "delete": "حذف",
    "deleteCard": "حذف البطاقة؟",
    "deleteCategory": "حذف الفئة",
    "deleteContact": "حذف جهة الاتصال",
    "deleteReward": "حذف المكافأة؟",
    "descending": "تنازلي",
    "description": "الوصف",
    "descriptionOptional": "الوصف (اختياري)",
    "details": "التفاصيل",
    "deviceLinked": "تم ربط الجهاز",
    "deviceLoggedOut": "تم تسجيل خروج الجهاز",
    "deviceStatus": "حالة الجهاز",
    "digitalBusinessCard": "بطاقة أعمال رقمية",
    "digitalBUSINESSCard": "بطاقة أعمال رقمية",
    "dontHaveAnAccount": "ليس لديك حساب؟",
    "eGFastFood": "مثال: وجبات سريعة",
    "eGNoSugarExtraHot": "مثال: بدون سكر، ساخن جدًا...",
    "earned50Points": "حصلت على 50 نقطة",
    "edit": "تعديل",
    "editCard": "تعديل البطاقة",
    "editDetails": "تعديل التفاصيل",
    "editProfile2": "تعديل الملف",
    "editSettings": "تعديل الإعدادات",
    "editYourProfileDetails": "تعديل بيانات ملفك",
    "email": "البريد الإلكتروني",
    "emailPassword": "البريد وكلمة المرور",
    "emailAddress": "البريد الإلكتروني",
    "emailLoginOrScanQR": "تسجيل الدخول بالبريد أو مسح QR",
    "employeeCard": "بطاقة الموظف",
    "employeeCARD": "بطاقة موظف",
    "employeeFacePhoto": "صورة وجه الموظف",
    "emptySlot": "خانة فارغة",
    "end": "النهاية",
    "endDate": "تاريخ الانتهاء",
    "endHour": "ساعة الانتهاء",
    "enrollCustomer": "تسجيل عميل",
    "enterBillAmount": "أدخل مبلغ الفاتورة",
    "enterCode": "أدخل الرمز",
    "enterCodeInstead": "إدخال الرمز بدلًا من ذلك",
    "enterNetworkingContactDetailsBelow": "أدخل بيانات جهة اتصال الشبكة أدناه.",
    "enterYourName": "أدخل اسمك",
    "enterYourPassword": "أدخل كلمة المرور",
    "eventBadge": "شارة الفعالية",
    "exchangeContact": "تبادل جهة الاتصال",
    "exchangingContact": "جارٍ تبادل جهة الاتصال...",
    "explore": "استكشاف",
    "failedToUpdateContact": "فشل تحديث جهة الاتصال.",
    "filledSlot": "خانة ممتلئة",
    "filterContacts": "تصفية جهات الاتصال",
    "filterContacts2": "تصفية جهات الاتصال",
    "findPeopleOnBarQody": "العثور على أشخاص على BarQody",
    "findUser": "البحث عن مستخدم",
    "findUser2": "البحث عن مستخدم",
    "findUsername": "البحث عن اسم مستخدم",
    "forgot": "نسيت؟",
    "freeCoffee": "قهوة مجانية",
    "fullName": "الاسم الكامل",
    "general": "عام",
    "go": "انتقال",
    "goBusiness": "الانتقال للأعمال",
    "guest": "زائر",
    "hello": "مرحبًا،",
    "helpCenterIsDisabledInThisUIDemo": "مركز المساعدة معطّل في هذا العرض التجريبي.",
    "hex": "Hex: #",
    "holdTheQRCodeInsideTheFrameItScansAutomatically": "ضع رمز QR داخل الإطار — يُمسح تلقائيًا.",
    "howDoYouWantToDesignThisCard": "كيف تريد تصميم هذه البطاقة؟",
    "importContacts": "استيراد جهات الاتصال",
    "importContactsIsNotAvailableYet": "استيراد جهات الاتصال غير متاح بعد.",
    "inLabel": "في",
    "incomingOrders": "الطلبات الواردة",
    "invalidProfileURLScanAValidBarQodyCardOrQRCode": "رابط الملف غير صالح. امسح بطاقة BarQody أو رمز QR صالحًا.",
    "invalidQRCodeUseABarqodyLinkQR": "رمز QR غير صالح. استخدم رمز QR لرابط Barqody.",
    "inviteEmployeesSetShiftsAndTrackPresence": "دعوة الموظفين، وتعيين الورديات، وتتبع الحضور",
    "invitedYouToJoinAsEmployee": "دعاك للانضمام كموظف",
    "janeDoe": "Jane Doe",
    "janeCompanyCom": "jane@company.com",
    "jobTitle": "المسمى الوظيفي",
    "johnDoe": "John Doe",
    "johnSmith": "John Smith",
    "johnEmailCom": "john@email.com",
    "joinedJan152026": "تاريخ الانضمام: 15 يناير 2026",
    "jpg": "JPG",
    "keepYourAccountSafeOnlyScanQRCodesWhenYouWantToLinkADeviceYouTrust": "حافظ على أمان حسابك. امسح رموز QR فقط عند ربط جهاز تثق به.",
    "label": "التسمية",
    "lat": "خط العرض",
    "letOthersPointTheirPhoneCameraToThisQRCodeToInstantlyViewYourNetworkingProfile": "دع الآخرين يوجّهون كاميرا هواتفهم إلى رمز QR هذا لعرض ملفك فورًا.",
    "link": "رابط",
    "linkADevice": "ربط جهاز",
    "linkByQROnAnotherPhone": "الربط عبر QR من هاتف آخر",
    "linkCopiedToClipboard": "تم نسخ الرابط إلى الحافظة",
    "linkSettings": "إعدادات الرابط",
    "linkSettings2": "إعدادات الرابط",
    "linkThisDevice": "ربط هذا الجهاز؟",
    "links": "الروابط",
    "linksOnThisCard": "الروابط في هذه البطاقة",
    "locationNotSetYet": "لم يُعيَّن الموقع بعد",
    "locationPermissionRequired": "إذن الموقع مطلوب",
    "locationPermissionRequiredForAttendance": "إذن الموقع مطلوب للحضور",
    "logIn": "تسجيل الدخول",
    "logInToManageYourDigitalCardAndNetwork": "سجّل الدخول لإدارة بطاقتك الرقمية وشبكتك.",
    "logInWithQRCode": "تسجيل الدخول برمز QR",
    "logOut2": "تسجيل الخروج",
    "logOutAll": "تسجيل الخروج من الكل",
    "logOutDevice": "تسجيل خروج الجهاز؟",
    "loyaltyPrograms": "برامج الولاء",
    "manageCategories": "إدارة الفئات",
    "manageContact": "إدارة جهة الاتصال",
    "manageEmployees": "إدارة الموظفين",
    "manageYourPersonalDetailsOtherPreferences": "إدارة بياناتك الشخصية والتفضيلات الأخرى",
    "markCompleted": "تعليم كمكتمل",
    "monthly": "شهري",
    "myCards": "بطاقاتي",
    "myLocation": "موقعي",
    "myRewards": "مكافآتي",
    "name": "الاسم",
    "name2": "الاسم",
    "nameIsRequired": "الاسم مطلوب",
    "nameCompanyCom": "name@company.com",
    "newCard": "بطاقة جديدة",
    "newCard2": "بطاقة جديدة",
    "newCategory": "فئة جديدة",
    "newReward": "مكافأة جديدة",
    "next": "التالي",
    "nextCard": "البطاقة التالية",
    "noActiveLinksConnectedYet": "لا توجد روابط نشطة بعد",
    "noActiveRewardProgramsAvailable": "لا توجد برامج مكافآت نشطة.",
    "noEmployeeCardsYet": "لا توجد بطاقات موظفين بعد",
    "noEmployeesAdded": "لم يُضف أي موظف",
    "noEmployeesYet": "لا يوجد موظفون بعد",
    "noEmployerFound": "لم يُعثر على جهة عمل",
    "noItemsInThisCategory": "لا عناصر في هذه الفئة.",
    "noLinkTemplatesAvailable": "لا قوالب روابط متاحة",
    "noNewNotificationsAtThisTime": "لا إشعارات جديدة حاليًا.",
    "noOneHasViewedYourProfileYet": "لم يعرض أحد ملفك بعد.",
    "noPendingInvitations": "لا دعوات معلّقة",
    "noProgramsAssignedYetAddProgramsBelow": "لا برامج معيَّنة بعد. أضف البرامج أدناه.",
    "noQRCodeFoundInThisImage": "لم يُعثر على رمز QR في هذه الصورة.",
    "noRewardProgramsYet": "لا برامج مكافآت بعد",
    "noSlotsAvailableOnThisDay": "لا أوقات متاحة في هذا اليوم",
    "noUsersFound": "لم يُعثر على مستخدمين",
    "none": "لا شيء",
    "notAvailableOnYourCurrentPlan": "غير متاح في باقتك الحالية",
    "notCheckedInYet": "لم يتم تسجيل الحضور بعد",
    "note": "ملاحظة",
    "notesOptional": "ملاحظات (اختياري)",
    "notificationCleared": "تم مسح الإشعار",
    "onlyCoverProfilePhotoNameAndBioAreEditableHere": "يمكن تعديل الغلاف وصورة الملف والاسم والنبذة فقط هنا.",
    "onlyEnabledLinksShowWhenSomeoneScansThisCard": "تظهر الروابط المفعّلة فقط عند مسح هذه البطاقة.",
    "onlyPublicProfilesAreShown": "تُعرض الملفات العامة فقط",
    "onlyThisPhoneIsUsingYourAccountRightNow": "هذا الهاتف وحده يستخدم حسابك حاليًا.",
    "orCONTINUEWITH": "أو المتابعة عبر",
    "order": "طلب",
    "orderDetails": "تفاصيل الطلب",
    "orderID": "رقم الطلب",
    "orderNotFound": "الطلب غير موجود",
    "orders": "الطلبات",
    "paperCard": "بطاقة ورقية",
    "password": "كلمة المرور",
    "payMonthByMonth": "الدفع شهريًا",
    "pendingACCEPTANCE": "بانتظار القبول",
    "performanceOverview": "نظرة على الأداء",
    "personalDetails": "البيانات الشخصية",
    "phone": "الهاتف",
    "photos": "الصور",
    "pickAReadyMadeColorThemeQuickAndClean": "اختر سمة ألوان جاهزة. سريعة وأنيقة.",
    "pickColor": "اختيار لون",
    "pickOnMap": "تحديد على الخريطة",
    "placeOrder": "تقديم الطلب",
    "planExpired": "انتهت الباقة",
    "pleaseEnterBusinessDetailsToContinue": "يرجى إدخال بيانات النشاط للمتابعة",
    "pleaseEnterItemName": "يرجى إدخال اسم العنصر",
    "pleaseProvideYourBusinessDetailsBeforeUpgrading": "يرجى إدخال بيانات نشاطك قبل الترقية.",
    "pleaseSelectACategory": "يرجى اختيار فئة",
    "pleaseSelectATimeSlot": "يرجى اختيار وقت",
    "pleaseSetWorkLocationFirst": "يرجى تعيين موقع العمل أولًا",
    "png": "PNG",
    "pointYourCameraAtTheQRCodeOnTheOtherDevice": "وجّه الكاميرا إلى رمز QR على الجهاز الآخر",
    "points": "النقاط",
    "pointsEarned": "النقاط المكتسبة",
    "premiumActive": "الاشتراك المميز نشط",
    "previousCard": "البطاقة السابقة",
    "priceRs": "السعر (ر.ب)",
    "pro": "PRO",
    "proTemplate": "قالب PRO",
    "profile": "الملف الشخصي",
    "profileCheck": "فحص الملف",
    "profileStrength": "قوة الملف",
    "profileViewers": "مشاهدو الملف",
    "profileViews": "مشاهدات الملف",
    "programDetails": "تفاصيل البرنامج",
    "programName": "اسم البرنامج",
    "programNotFound": "البرنامج غير موجود",
    "programType": "نوع البرنامج",
    "qrCode": "رمز QR",
    "qrScans": "عمليات مسح QR",
    "quantity": "الكمية",
    "readAll": "قراءة الكل",
    "readOnly2": "للقراءة فقط",
    "received1Stamp": "حصلت على طابع واحد",
    "recentActivity": "النشاط الأخير",
    "redeemAnotherReward": "استبدال مكافأة أخرى",
    "redeemReward": "استبدال المكافأة",
    "redeemedFreeCoffee": "تم استبدال قهوة مجانية",
    "refreshQR": "تحديث QR",
    "region": "المنطقة",
    "rembiro": "Rembiro",
    "remove": "إزالة",
    "removeEmployee": "إزالة موظف",
    "renewPlan": "تجديد الباقة",
    "requestPending": "الطلب معلّق",
    "requestPending2": "الطلب معلّق",
    "requestRejected": "تم رفض الطلب",
    "requestSubscription": "طلب اشتراك",
    "reset": "إعادة تعيين",
    "rewardCompletedShowThisCardToRedeem": "اكتملت المكافأة! اعرض هذه البطاقة للاستبدال.",
    "rewardCompleted": "اكتملت المكافأة! 🎉",
    "rewardDetails": "تفاصيل المكافأة",
    "rewardProgram": "برنامج المكافآت",
    "rewardPrograms": "برامج المكافآت",
    "rewardRedeemed": "تم استبدال المكافأة!",
    "rewards": "المكافآت",
    "rewardsEarned": "المكافآت المكتسبة",
    "rs1600BilledMonthly": "‏1,600 ر.ب تُحتسب شهريًا",
    "rs8300BilledYearly": "‏8,300 ر.ب تُحتسب سنويًا",
    "saimyousufYGmailCom": "saimyousuf.y@gmail.com",
    "save2": "حفظ",
    "saveYourWorkIDCardToPhoneOrWallet": "احفظ بطاقة العمل على الهاتف أو المحفظة",
    "scan": "مسح",
    "scanAUserQRCodeToAddThemAsEmployee": "امسح رمز QR للمستخدم لإضافته كموظف",
    "scanAnyUserOrBusinessQRToAddEmployee": "امسح أي رمز QR لمستخدم أو نشاط لإضافة موظف",
    "scanBusinessQRToRedeem": "امسح رمز QR للنشاط للاستبدال",
    "scanCustomerQRCode": "مسح رمز QR للعميل",
    "scanEmployeeProfile": "مسح ملف الموظف",
    "scanQR": "مسح QR",
    "scanQRShowQR": "مسح QR / عرض QR",
    "scanQRCode": "مسح رمز QR",
    "scanQRShownOnTheOtherDevice": "امسح رمز QR المعروض على الجهاز الآخر",
    "scanToInvite": "مسح للدعوة",
    "searchByUsername": "البحث باسم المستخدم...",
    "searchLinks": "بحث في الروابط",
    "searchNameEmailOrCompany": "ابحث بالاسم أو البريد أو الشركة",
    "seeAll": "عرض الكل",
    "seeAllActivityIsMockedNewActivitiesWillAppearAsLeadsAreAdded": "عرض كل النشاط تجريبي. ستظهر الأنشطة الجديدة عند إضافة العملاء المحتملين.",
    "selectDate": "اختيار التاريخ",
    "selectMarkers": "اختيار العلامات",
    "selectRegion": "اختيار المنطقة",
    "setTextUnderTheLinkIcon": "تعيين النص أسفل أيقونة الرابط",
    "setYourOwnColorsPhotosAndBackground": "عيّن ألوانك وصورك وخلفيتك.",
    "share": "مشاركة",
    "shareCard": "مشاركة البطاقة",
    "shareDifferentLinksOnEachCard": "مشاركة روابط مختلفة في كل بطاقة",
    "shareProfile": "مشاركة الملف",
    "showLink": "إظهار الرابط",
    "showOnThisCard": "إظهار في هذه البطاقة",
    "signInWithGoogle": "تسجيل الدخول عبر Google",
    "signUp": "إنشاء حساب",
    "skip": "تخطي",
    "skipForNow": "تخطي الآن",
    "slotMin": "المدة (دقيقة)",
    "softwareEngineer": "مهندس برمجيات",
    "somethingWentWrong": "حدث خطأ ما",
    "sortOptions": "خيارات الترتيب",
    "specialInstructions": "تعليمات خاصة",
    "stampCard": "بطاقة طوابع",
    "stampIcon": "أيقونة الطابع",
    "stamps": "الطوابع",
    "start": "البداية",
    "startDate": "تاريخ البدء",
    "startHour": "ساعة البدء",
    "startNetworkingSmarterWithBarqody": "ابدأ التواصل بذكاء أكبر مع Barqody.",
    "stats": "الإحصاءات",
    "status": "الحالة",
    "subscription": "الاشتراك",
    "subscriptionRequestSubmitted": "تم إرسال طلب الاشتراك",
    "subscriptionRequestSubmitted2": "تم إرسال طلب الاشتراك.",
    "swipeToBrowseCards": "مرّر لاستعراض البطاقات",
    "takeAQuickSelfieForAttendanceVerification": "التقط صورة سريعة للتحقق من الحضور",
    "tapSocialLinksAboveToAddAndActivateProfiles": "اضغط على «روابط التواصل» أعلاه لإضافة الملفات وتفعيلها.",
    "tapOnTheMapOrUseYourCurrentLocation": "اضغط على الخريطة أو استخدم موقعك الحالي",
    "tapToAddPhoto": "اضغط لإضافة صورة",
    "tapToShareQRCode": "اضغط لمشاركة رمز QR",
    "tapni": "tapni",
    "teamAttendance": "حضور الفريق",
    "template": "قالب",
    "templates": "القوالب",
    "thankYouFeedbackSubmissionsAreMockOnly": "شكرًا لك! إرسال الملاحظات تجريبي فقط.",
    "thisCardAndItsQRCodeWillBeRemoved": "ستُزال هذه البطاقة ورمز QR الخاص بها.",
    "thisFeatureIsExclusivelyAvailableToBusinessUsers": "هذه الميزة متاحة لمستخدمي الأعمال فقط.",
    "thisIsAlreadyYourUsername": "هذا اسم المستخدم الحالي بالفعل.",
    "thisMonth": "هذا الشهر",
    "thisWillPermanentlyDeleteThisRewardProgramAndAllItsEnrollments": "سيُحذف برنامج المكافآت هذا وجميع تسجيلاته نهائيًا.",
    "todayIsYourWeekend": "اليوم عطلتك",
    "today315PM": "اليوم • 3:15 م",
    "total": "الإجمالي",
    "trackYourOrders": "متابعة طلباتك",
    "transactionReferenceOptional": "مرجع التحويل (اختياري)",
    "transactionReferenceNumberOptional": "رقم مرجع التحويل (اختياري)",
    "tryAgain": "إعادة المحاولة",
    "tryBusinessPro": "جرّب Business Pro",
    "tryBusinessPro2": "جرّب Business Pro.",
    "type": "النوع",
    "typeAtLeast2CharactersOfAUsernameToSearch": "اكتب حرفين على الأقل من اسم المستخدم للبحث.",
    "typeThe8CharacterCodeShownUnderTheQR": "اكتب الرمز المكوّن من 8 أحرف الظاهر أسفل QR.",
    "underDevelopmentLoginViaEmailPasswordInstead": "قيد التطوير — سجّل الدخول بالبريد وكلمة المرور بدلًا من ذلك.",
    "unstampIcon": "أيقونة بدون طابع",
    "upgradeNow": "الترقية الآن",
    "upgradeTo": "الترقية إلى",
    "upgradeToTapniPRO": "الترقية إلى Tapni PRO",
    "useATemplate": "استخدام قالب",
    "useBarqodyOnOtherPhonesOrTabletsYouStayInControlLogOutAnyDeviceAnytime": "استخدم Barqody على هواتف أو أجهزة لوحية أخرى. تبقى أنت المتحكم — سجّل الخروج من أي جهاز في أي وقت.",
    "useBarqodyOnYourPhoneToScanThisCode": "استخدم Barqody على هاتفك لمسح هذا الرمز",
    "useDefaultIcon": "استخدام الأيقونة الافتراضية",
    "useThisPhoto": "استخدام هذه الصورة",
    "user": "مستخدم",
    "version101": "الإصدار: 1.0.1",
    "viewAndUpdateOrdersFromYourCustomers": "عرض طلبات عملائك وتحديثها",
    "viewProfile": "عرض الملف",
    "views": "المشاهدات",
    "website": "الموقع",
    "welcomeBack": "مرحبًا بعودتك",
    "welcomeToAccountCenter": "مرحبًا بك في مركز الحسابات",
    "whenABusinessAddsYouAsEmployeeYourEmployeeCardWillAppearHereYouCanCustomizeItsDe": "عند إضافتك كموظف من نشاط تجاري، ستظهر بطاقة الموظف هنا. يمكنك تخصيص تصميمها في أي وقت.",
    "whenABusinessEnrollsYouInTheirRewardProgramItWillAppearHere": "عند تسجيلك في برنامج مكافآت لنشاط تجاري، سيظهر هنا.",
    "whenABusinessInvitesYouToTheirTeamItWillAppearHere": "عند دعوتك للانضمام إلى فريق نشاط تجاري، ستظهر الدعوة هنا.",
    "whenTurnedOffThisLinkWontBeShownOnYourProfile": "عند إيقافه لن يظهر هذا الرابط في ملفك",
    "writeSomethingAboutYouOrYourBrand": "اكتب شيئًا عنك أو عن علامتك",
    "yearly": "سنوي",
    "yesterday542PM": "أمس • 5:42 م",
    "yourCategories": "فئاتك",
    "yourEmployeeCardsFromEmployers": "بطاقات الموظف من جهات العمل",
    "yourFreeCoffeeHasBeenSuccessfullyRedeemed": "تم استبدال قهوتك المجانية بنجاح.",
    "yourRewards": "مكافآتك",
    "yourSubscriptionHasEndedTapTheInfoIconForDetails": "انتهى اشتراكك. اضغط أيقونة المعلومات للتفاصيل.",
    "yourname": "yourname",
    "n10Discount": "خصم 10٪",
    "avatarTAPPED": "تم الضغط على الصورة",
    "accountHolderName": "اسم صاحب الحساب",
    "accountNumber": "رقم الحساب",
    "activeNow": "نشط الآن",
    "addBio": "إضافة نبذة",
    "addCoverPhoto": "إضافة صورة غلاف",
    "addFacePhoto": "إضافة صورة وجه",
    "addIntroVoiceNote": "إضافة مقدمة صوتية",
    "addProfileName": "إضافة اسم الملف",
    "addProfilePhoto": "إضافة صورة الملف",
    "addSocialLinks3": "إضافة روابط تواصل (3+)",
    "addItem": "إضافة عنصر",
    "addLink2": "إضافة رابط",
    "addLinksToYourProfileBelow2": "أضف الروابط إلى ملفك أدناه ",
    "addPhoto": "إضافة صورة",
    "addToCart": "إضافة إلى السلة",
    "addressOptional": "العنوان (اختياري)",
    "allContactTypes": "كل أنواع جهات الاتصال",
    "allowedRadiusMeters": "نصف القطر المسموح (متر)",
    "almostThere": "أوشكت على الانتهاء!",
    "alreadyEmployee": "موظف بالفعل",
    "alreadyHaveAnAccount2": "لديك حساب بالفعل؟ ",
    "alwaysUpToDate": "دائمًا محدّث",
    "areYouSureYouWantToLogOutOfBarqody": "هل أنت متأكد من تسجيل الخروج من Barqody؟",
    "attendanceFailed": "فشل تسجيل الحضور",
    "backgroundColor2": "لون الخلفية",
    "bookingFailed": "فشل الحجز",
    "brieflyDescribeThisReward": "صف هذه المكافأة باختصار...",
    "businessVerified": "نشاط موثّق",
    "businessEmailAddress": "البريد الإلكتروني للنشاط",
    "businessFax": "فاكس النشاط",
    "businessPhoneNumber": "هاتف النشاط",
    "businessWebsite": "موقع النشاط",
    "cameraError": "خطأ في الكاميرا",
    "captureFace": "التقاط الوجه",
    "cardCompleted": "اكتملت البطاقة",
    "cardLabel": "تسمية البطاقة",
    "cardLabelName": "اسم تسمية البطاقة",
    "cardPreview": "معاينة البطاقة",
    "cardTheme": "سمة البطاقة",
    "cardCreated": "تم إنشاء البطاقة",
    "cardName": "اسم البطاقة",
    "cardSavedAsJPG": "تم حفظ البطاقة بصيغة JPG",
    "cardSavedAsPNG": "تم حفظ البطاقة بصيغة PNG",
    "cardUpdated": "تم تحديث البطاقة",
    "changePhoto": "تغيير الصورة",
    "checkInFace": "وجه تسجيل الحضور",
    "checkInSuccessful": "تم تسجيل الحضور بنجاح",
    "checkOutFace": "وجه تسجيل الانصراف",
    "checkOutSuccessful": "تم تسجيل الانصراف بنجاح",
    "chooseTemplate2": "اختيار قالب",
    "contactCardBusinessAddress": "عنوان النشاط في بطاقة الاتصال",
    "contactCardCompanyName": "اسم الشركة في بطاقة الاتصال",
    "contactCardEmail": "البريد في بطاقة الاتصال",
    "contactCardHomeAddress": "عنوان المنزل في بطاقة الاتصال",
    "contactCardPhone": "الهاتف في بطاقة الاتصال",
    "contactCardWebsite": "الموقع في بطاقة الاتصال",
    "couldNotCompleteLogin": "تعذّر إكمال تسجيل الدخول",
    "couldNotCreateQRCode": "تعذّر إنشاء رمز QR",
    "couldNotLinkDevice": "تعذّر ربط الجهاز",
    "couldNotLogOutDevice": "تعذّر تسجيل خروج الجهاز",
    "couldNotOpenGoogleWallet": "تعذّر فتح Google Wallet",
    "couldNotSaveCardDesign": "تعذّر حفظ تصميم البطاقة",
    "couldNotUpdateProfileVisibility": "تعذّر تحديث ظهور الملف",
    "createGallery": "إنشاء معرض",
    "createACardToShareYourProfile": "أنشئ بطاقة لمشاركة ملفك",
    "createCard": "إنشاء بطاقة",
    "customBank": "بنك مخصص",
    "customersCanBeEnrolledAndStamped": "يمكن تسجيل العملاء وإضافة الطوابع لهم",
    "customizeCard": "تخصيص البطاقة",
    "describeYourLoyaltyProgram": "صف برنامج الولاء الخاص بك",
    "displayName": "اسم العرض",
    "dontHaveAnAccount2": "ليس لديك حساب؟ ",
    "eeeDMMMYyyy": "EEE, d MMM yyyy",
    "editReward": "تعديل المكافأة",
    "editItem": "تعديل العنصر",
    "emailAddress2": "البريد الإلكتروني",
    "emailIsRequired": "البريد الإلكتروني مطلوب",
    "employeeCards": "بطاقات الموظفين",
    "employeeRemoved": "تمت إزالة الموظف",
    "employeeSettingsSaved": "تم حفظ إعدادات الموظف",
    "enrolledBusinesses": "الأنشطة المسجّلة",
    "enterAValidEmail": "أدخل بريدًا إلكترونيًا صالحًا",
    "enterBioForTheContactCard": "أدخل نبذة لبطاقة الاتصال",
    "enterProgramName": "أدخل اسم البرنامج",
    "enterYourBio": "أدخل نبذتك",
    "enterYourPhoneNumber": "أدخل رقم هاتفك",
    "enterYourWebsiteURL": "أدخل رابط موقعك",
    "eventBadge2": "شارة الفعالية",
    "example10StampsFreeCoffee": "مثال: 10 طوابع = قهوة مجانية",
    "facePhotoAdded": "تمت إضافة صورة الوجه",
    "failedToAddProgram": "فشل إضافة البرنامج",
    "failedToAddStamp": "فشل إضافة الطابع",
    "failedToEnrollCustomer": "فشل تسجيل العميل",
    "failedToExchangeContact": "فشل تبادل جهة الاتصال",
    "failedToLoadPrograms": "فشل تحميل البرامج",
    "failedToPlaceOrder": "فشل تقديم الطلب",
    "failedToRemove": "فشلت الإزالة",
    "failedToSave": "فشل الحفظ",
    "failedToSaveJPG": "فشل حفظ JPG",
    "failedToSavePNG": "فشل حفظ PNG",
    "failedToSaveQRCode": "فشل حفظ رمز QR.",
    "failedToSaveBusinessDetails": "فشل حفظ بيانات النشاط",
    "failedToUpdateStatus": "فشل تحديث الحالة",
    "firstName": "الاسم الأول",
    "foodBeverage": "أطعمة ومشروبات",
    "freeDessert": "حلوى مجانية",
    "galleryPermissionRequiredPleaseEnableItInSettings": "إذن المعرض مطلوب. يرجى تفعيله من الإعدادات.",
    "getStarted": "البدء",
    "go2": "انتقال ",
    "goToToolsLinkedDevices": "انتقل إلى الأدوات ← الأجهزة المرتبطة",
    "googleWalletSetupPending": "إعداد Google Wallet معلّق.",
    "googleWalletSetupPendingProfileLinkCopied": "إعداد Google Wallet معلّق. تم نسخ رابط الملف.",
    "growYourBusiness": "نمِّ نشاطك",
    "guestUser": "مستخدم زائر",
    "ibanNumber": "رقم IBAN",
    "inOFFICE": "في المكتب",
    "invitationPending": "الدعوة معلّقة",
    "invitationDeclined": "تم رفض الدعوة",
    "invitationSentEmployeeWillBeAddedAfterTheyAccept": "تم إرسال الدعوة. سيُضاف الموظف بعد القبول.",
    "inviteEmployee": "دعوة موظف",
    "inviteAsEmployee": "دعوة كموظف",
    "jobTitle2": "المسمى الوظيفي",
    "lastName": "اسم العائلة",
    "logInWithQR": "تسجيل الدخول عبر QR",
    "logOutOfThisAccountOnlyOtherAccountsWillStayOnThisPhone": "تسجيل الخروج من هذا الحساب فقط؟ ستبقى الحسابات الأخرى على هذا الهاتف.",
    "loggedInWithGoogleDemoAccountSaimY": "تم تسجيل الدخول عبر Google (حساب تجريبي: Saim Y)",
    "loggingYouIn": "جارٍ تسجيل الدخول…",
    "loginFailedTryAgain": "فشل تسجيل الدخول. أعد المحاولة.",
    "mmmDYyyyHMmA": "MMM d, yyyy - h:mm a",
    "mmmmYyyy": "MMMM yyyy",
    "markAttendance": "تسجيل الحضور",
    "myName": "اسمي",
    "myTapniProfile": "ملفي على Tapni",
    "nameCannotBeEmpty": "لا يمكن أن يكون الاسم فارغًا",
    "newLabel": "جديد ",
    "noContactsYet": "لا جهات اتصال بعد",
    "noDetailsYet": "لا تفاصيل بعد",
    "noLinksAddedYetNTapAddLinkToGetStarted": "لم تُضف روابط بعد.\nاضغط «إضافة رابط» للبدء.",
    "noMatches": "لا نتائج",
    "noReasonProvided": "لم يُذكر سبب.",
    "notEnrolled": "غير مسجّل",
    "numberOfStamps": "عدد الطوابع",
    "oneTapToShare": "مشاركة بضغطة واحدة",
    "openBarqodyOnYourOtherPhone": "افتح Barqody على هاتفك الآخر",
    "openCamera": "فتح الكاميرا",
    "orderInfo": "معلومات الطلب",
    "paperCard2": "بطاقة ورقية",
    "passwordMustBeAtLeast4Characters": "يجب أن تكون كلمة المرور 4 أحرف على الأقل",
    "passwordMustBeAtLeast6Characters": "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
    "phoneNumber": "رقم الهاتف",
    "phoneIsRequired": "رقم الهاتف مطلوب",
    "phoneNumber2": "رقم الهاتف",
    "pickLocation": "اختيار الموقع",
    "pleaseEnterAPassword": "يرجى إدخال كلمة المرور",
    "pleaseEnterAUsername": "يرجى إدخال اسم المستخدم",
    "pleaseEnterAValidEmailAddress": "يرجى إدخال بريد إلكتروني صالح",
    "pleaseEnterAValidNumberOfStamps": "يرجى إدخال عدد طوابع صالح",
    "pleaseEnterYourEmail": "يرجى إدخال بريدك الإلكتروني",
    "pleaseEnterYourName": "يرجى إدخال اسمك",
    "pleaseEnterYourPassword": "يرجى إدخال كلمة المرور",
    "pointTheCameraAtAQRCodeToScanAutomatically": "وجّه الكاميرا إلى رمز QR للمسح التلقائي.",
    "pointTheCameraAtAnEventBadgeAndTapTheCameraButton": "وجّه الكاميرا إلى شارة الفعالية واضغط زر الكاميرا.",
    "pointTheCameraAtPaperCardAndTapTheCameraButton": "وجّه الكاميرا إلى البطاقة الورقية واضغط زر الكاميرا.",
    "preparingQRCode": "جارٍ تجهيز رمز QR…",
    "profileNotFound": "الملف غير موجود.",
    "profileUpdatedSuccessfully": "تم تحديث الملف بنجاح!",
    "qrCodeSavedToGallery": "تم حفظ رمز QR في المعرض!",
    "qrCodeExpired": "انتهت صلاحية رمز QR",
    "qrCodeExpiredTapRefresh": "انتهت صلاحية رمز QR. اضغط تحديث.",
    "realEstate": "عقارات",
    "receiptAttached": "تم إرفاق الإيصال",
    "renewYourSubscriptionToRestoreFullAccessToYourPremiumFeaturesAndData": "جدّد اشتراكك لاستعادة الوصول الكامل إلى الميزات والبيانات المميزة.",
    "retakePhoto": "إعادة التقاط الصورة",
    "rewardTitle": "عنوان المكافأة",
    "rewardUnlocked": "تم فتح المكافأة 🎉",
    "roleOrCompany": "الدور أو الشركة",
    "saveChanges": "حفظ التغييرات",
    "saveContact": "حفظ جهة الاتصال",
    "saveProfile": "حفظ الملف",
    "saveSettings": "حفظ الإعدادات",
    "saveUsername": "حفظ اسم المستخدم",
    "saveCard": "حفظ البطاقة",
    "saveContact2": "حفظ جهة الاتصال",
    "savedLocallySyncMayHaveFailed": "تم الحفظ محليًا. قد تكون المزامنة فشلت.",
    "scanAQRCodeOrAddSomeoneYouMetToBuildYourNetwork": "امسح رمز QR أو أضف شخصًا قابلته لبناء شبكتك.",
    "scannedViaQR": "تم المسح عبر QR",
    "screenTheme": "سمة الشاشة",
    "searchFailedTryAgain": "فشل البحث. أعد المحاولة.",
    "selectCompany": "اختيار الشركة",
    "selectDateRange": "اختيار نطاق التاريخ",
    "selectEndDate": "اختيار تاريخ الانتهاء",
    "selectStartDate": "اختيار تاريخ البدء",
    "sendInvitation": "إرسال دعوة",
    "sendInvitationForAttendance": "إرسال دعوة للحضور",
    "shareLink": "مشاركة الرابط",
    "shiftTiming": "توقيت الوردية",
    "smartContactCapture": "التقاط ذكي لجهات الاتصال",
    "stampBorderColor": "لون إطار الطابع",
    "stampColor": "لون الطابع",
    "stampIconsOptional": "أيقونات الطابع (اختياري)",
    "stampsGiven": "الطوابع الممنوحة",
    "startBuildingYourNetwork": "ابدأ ببناء شبكتك",
    "streetName": "اسم الشارع",
    "switchToABusinessAccountToUnlockFullAccess": "بدّل إلى حساب أعمال لفتح الوصول الكامل.",
    "tapLinkADeviceAndScanThisQR": "اضغط «ربط جهاز» وامسح رمز QR هذا",
    "tapToAddImage": "اضغط لإضافة صورة",
    "tapToChange": "اضغط للتغيير",
    "templateAppliedLocallySyncFailed": "تم تطبيق القالب محليًا. فشلت المزامنة.",
    "textColor": "لون النص",
    "thisAccount": "هذا الحساب",
    "thisFeatureIsExclusivelyAvailableToBusinessUsers2": "هذه الميزة متاحة لمستخدمي الأعمال فقط. ",
    "thisPersonIsOnYourTeam": "هذا الشخص في فريقك",
    "thisProgramIsPaused": "هذا البرنامج متوقف مؤقتًا",
    "totalStamps": "إجمالي الطوابع",
    "tryADifferentNameEmailOrCompany": "جرّب اسمًا أو بريدًا أو شركة مختلفة.",
    "unableToSaveProfileTryAgain": "تعذّر حفظ الملف. أعد المحاولة.",
    "unableToUpdateUsernameTryAgain": "تعذّر تحديث اسم المستخدم. أعد المحاولة.",
    "underDevelopmentLoginViaEmailPasswordInstead2": "قيد التطوير — سجّل الدخول بالبريد وكلمة المرور بدلًا من ذلك. ",
    "unknownUser": "مستخدم غير معروف",
    "updateGPSLocation": "تحديث موقع GPS",
    "updateStatus": "تحديث الحالة",
    "updateCart": "تحديث السلة",
    "updateItem": "تحديث العنصر",
    "upgradeTo2": "الترقية إلى ",
    "upgradeToBusinessPRO": "الترقية إلى Business PRO",
    "uploadReceiptOptional": "رفع إيصال (اختياري)",
    "useMyLocation": "استخدام موقعي",
    "useLettersNumbersUnderscoresOrHyphensOnly": "استخدم الأحرف والأرقام والشرطة السفلية أو الواصلة فقط",
    "usernameMustBeAtLeast3Characters": "يجب أن يكون اسم المستخدم 3 أحرف على الأقل",
    "usernameMustBeAtMost30Characters": "يجب ألا يتجاوز اسم المستخدم 30 حرفًا",
    "usernameUpdatedSuccessfully": "تم تحديث اسم المستخدم بنجاح!",
    "waitingForThemToAccept": "بانتظار قبولهم",
    "websiteURL": "رابط الموقع",
    "weekendDays": "أيام العطلة",
    "workLocation": "موقع العمل",
    "yourPROSubscriptionHasExpiredNN": "انتهى اشتراك PRO.\n\n",
    "yourPROSubscriptionHasExpired": "انتهى اشتراك PRO.",
    "premiumFeaturesAreCurrentlyDisabled": "الميزات المميزة معطّلة حاليًا.",
    "proLinksAreHiddenFromYourPublicProfile": "روابط PRO مخفية عن ملفك العام.",
    "yourBusinessDetailsAndDataAreSafe": "بيانات نشاطك وملفاتك بأمان.",
    "addCatalogItem": "إضافة عنصر {label}",
    "addAtLeastOneCatalogItem": "أضف عنصر {label} واحدًا على الأقل",
    "noCatalogItemsAvailable": "لا عناصر {label} متاحة.",
    "noItemsYetAddFirstCatalogItem": "لا عناصر بعد. أضف أول عنصر {label}.",
    "noPublicProfileMatchesQuery": "لا ملف عام يطابق \"@{query}\".",
    "codeWithValue": "الرمز: {code}",
    "eInvoice": "فاتورة إلكترونية",
    "eInvoiceDetails": "تفاصيل الفاتورة الإلكترونية",
    "saudiEInvoice": "الفاتورة الإلكترونية السعودية",
    "pointTheCameraAtAnyQRCodeWebsiteWifiOrProduct": "وجّه الكاميرا إلى أي رمز QR — موقع، Wi‑Fi، منتج، أو بطاقة BarQody.",
    "pointTheCameraAtASaudiEInvoiceQRCode": "وجّه الكاميرا إلى رمز QR لفاتورة ZATCA الإلكترونية السعودية.",
    "invalidEInvoiceQRScanAValidZATCAInvoiceQR": "رمز QR للفاتورة غير صالح. امسح رمز QR صالحًا لفاتورة ZATCA سعودية.",
    "scannedQr": "رمز QR الممسوح",
    "qrScanResultSubtitle": "المحتوى المستخرج من رمز QR",
    "scannedContent": "المحتوى الممسوح",
    "qrTypeWebsite": "موقع / رابط",
    "qrTypeWifi": "Wi‑Fi",
    "qrTypeEmail": "بريد إلكتروني",
    "qrTypePhone": "هاتف",
    "qrTypeSms": "SMS",
    "qrTypeText": "نص / منتج",
    "wifiNetwork": "اسم الشبكة (SSID)",
    "wifiPassword": "كلمة المرور",
    "wifiSecurity": "الأمان",
    "openLink": "فتح الرابط",
    "openEmail": "فتح البريد",
    "callNumber": "اتصال بالرقم",
    "sendSms": "إرسال SMS",
    "copyContent": "نسخ المحتوى",
    "copiedToClipboard": "تم النسخ إلى الحافظة",
    "couldNotOpenLink": "تعذّر فتح هذا الرابط.",
    "sellerName": "اسم البائع",
    "vatRegistrationNumber": "رقم تسجيل VAT",
    "invoiceDateTime": "تاريخ ووقت الفاتورة",
    "invoiceTotal": "إجمالي الفاتورة",
    "vatAmount": "مبلغ VAT",
    "invoiceHash": "تجزئة الفاتورة",
    "copyAllDetails": "نسخ كل التفاصيل",
    "zatcaPhase1Invoice": "فاتورة ZATCA المرحلة 1",
    "zatcaPhase2Supported": "دعم ZATCA المرحلة 2",
    "invitations": "الدعوات",
    "invitationsSubtitle": "إرسال وإدارة دعوات جهات الاتصال",
    "invitation": "دعوة",
    "searchEllipsis": "بحث...",
    "unreadCountLabel": "{count} غير مقروء",
    "unlockBusinessProDescription": "افتح طلبات العملاء وحضور الفريق وبرامج الولاء والمزيد لعملك.",
    "received": "الواردة",
    "sent": "المرسلة",
    "noInvitationsYet": "لا توجد دعوات بعد",
    "whenSomeoneInvitesYouItWillShowUpHere": "عندما يدعوك أحد، ستظهر الدعوة هنا.",
    "noSentInvitations": "لا توجد دعوات مرسلة",
    "createInvitationSaveDraftOrSendHint": "أنشئ دعوة، احفظها كمسودة، أو أرسلها لجهات الاتصال.",
    "noCardsYet": "لا بطاقات بعد",
    "designAnInvitationItWillAppearHere": "صمّم دعوة — ستظهر هنا",
    "contactsOnBarqody": "جهات الاتصال على Barqody",
    "inviteToBarqody": "دعوة إلى Barqody",
    "onBarqody": "على Barqody",
}

PLACEHOLDER_RE = re.compile(r"\{[^}]+\}")


def main() -> int:
    en = json.loads(EN_ARB.read_text(encoding="utf-8"))
    string_keys = [k for k in en if not k.startswith("@") and k != "@@locale"]
    missing = [k for k in string_keys if k not in AR]
    extra = [k for k in AR if k not in string_keys]
    if missing or extra or len(AR) != len(string_keys):
        print(
            f"Key mismatch: en={len(string_keys)} ar={len(AR)} "
            f"missing={len(missing)} extra={len(extra)}",
            file=sys.stderr,
        )
        if missing:
            print("Missing:", missing[:40], file=sys.stderr)
        if extra:
            print("Extra:", extra[:40], file=sys.stderr)
        return 1

    out: OrderedDict = OrderedDict()
    out["@@locale"] = "ar"
    for key, value in en.items():
        if key == "@@locale":
            continue
        if key.startswith("@"):
            out[key] = value
        else:
            ar_val = AR[key]
            en_ph = PLACEHOLDER_RE.findall(value if isinstance(value, str) else "")
            ar_ph = PLACEHOLDER_RE.findall(ar_val)
            if en_ph != ar_ph:
                print(
                    f"Placeholder mismatch for {key}: en={en_ph} ar={ar_ph}",
                    file=sys.stderr,
                )
                return 1
            out[key] = ar_val

    AR_ARB.write_text(
        json.dumps(out, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {AR_ARB} with {len(string_keys)} string keys")

    checks = {
        "cancel": "إلغاء",
        "save": "حفظ",
        "done": "تم",
        "accept": "قبول",
        "add": "إضافة",
        "str": "بطاقة الأعمال الرقمية",
    }
    for k, expected in checks.items():
        if AR[k] != expected:
            print(
                f"Spot-check failed: {k}={AR[k]!r} expected {expected!r}",
                file=sys.stderr,
            )
            return 1
    print("Spot-checks OK:", ", ".join(f"{k}={v}" for k, v in checks.items()))

    if EN_KEYS_JSON.exists():
        EN_KEYS_JSON.unlink()
        print(f"Deleted {EN_KEYS_JSON}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
