import 'package:tapni_app/models/business_card_design.dart';
import 'package:tapni_app/models/invitation_design.dart';

/// Built-in vertical business card templates (same orientation as digital cards).
class BusinessCardDesignCatalog {
  static String _nid(String prefix, int i) => '${prefix}_$i';

  static List<BusinessCardTemplate> get all => [
        BusinessCardTemplate(
          id: 'bc_navy',
          name: 'Navy Classic',
          category: 'professional',
          build: _navyClassic,
        ),
        BusinessCardTemplate(
          id: 'bc_minimal',
          name: 'Minimal Light',
          category: 'minimal',
          build: _minimalLight,
        ),
        BusinessCardTemplate(
          id: 'bc_bold',
          name: 'Bold Accent',
          category: 'modern',
          build: _boldAccent,
        ),
        BusinessCardTemplate(
          id: 'bc_dark',
          name: 'Dark Elegant',
          category: 'elegant',
          build: _darkElegant,
        ),
        BusinessCardTemplate(
          id: 'bc_split',
          name: 'Split Header',
          category: 'modern',
          build: _splitHeader,
        ),
        BusinessCardTemplate(
          id: 'bc_qr_focus',
          name: 'QR Focus',
          category: 'qr',
          build: _qrFocus,
        ),
        BusinessCardTemplate(
          id: 'bc_coral',
          name: 'Coral Soft',
          category: 'creative',
          build: _coralSoft,
        ),
        BusinessCardTemplate(
          id: 'bc_mono',
          name: 'Mono Clean',
          category: 'minimal',
          build: _monoClean,
        ),
      ];

  static BusinessCardDesign byId(String id) {
    final t = all.where((e) => e.id == id);
    if (t.isEmpty) return _navyClassic();
    return t.first.build();
  }

  static BusinessCardDesign _navyClassic() {
    final id = 'bc_navy';
    var z = 0;
    return BusinessCardDesign(
      templateId: id,
      category: 'professional',
      backgroundColor: '#0F172A',
      layers: [
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.shape,
          x: 0,
          y: 0,
          width: 1,
          height: 0.02,
          zIndex: z++,
          color: '#38BDF8',
          shape: 'rect',
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'name',
          text: 'Your Name',
          x: 0.08,
          y: 0.12,
          width: 0.84,
          height: 0.1,
          zIndex: z++,
          fontFamily: 'cairo',
          fontSize: 0.07,
          color: '#FFFFFF',
          bold: true,
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'title',
          text: 'Job Title',
          x: 0.1,
          y: 0.23,
          width: 0.8,
          height: 0.06,
          zIndex: z++,
          fontFamily: 'cairo',
          fontSize: 0.038,
          color: '#94A3B8',
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'company',
          text: 'Company',
          x: 0.1,
          y: 0.3,
          width: 0.8,
          height: 0.05,
          zIndex: z++,
          fontSize: 0.032,
          color: '#38BDF8',
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.qr,
          fieldKey: 'qr',
          qrData: 'https://tapni.com',
          qrColor: '#0F172A',
          x: 0.28,
          y: 0.4,
          width: 0.44,
          height: 0.28,
          zIndex: z++,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.iconField,
          fieldKey: 'phone',
          text: '+1 234 567 890',
          iconName: 'phone',
          x: 0.12,
          y: 0.74,
          width: 0.76,
          height: 0.08,
          zIndex: z++,
          fontSize: 0.028,
          color: '#E2E8F0',
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.iconField,
          fieldKey: 'email',
          text: 'hello@email.com',
          iconName: 'email',
          x: 0.12,
          y: 0.84,
          width: 0.76,
          height: 0.08,
          zIndex: z++,
          fontSize: 0.028,
          color: '#E2E8F0',
          align: DesignTextAlign.center,
        ),
      ],
    );
  }

  static BusinessCardDesign _minimalLight() {
    final id = 'bc_minimal';
    var z = 0;
    return BusinessCardDesign(
      templateId: id,
      category: 'minimal',
      backgroundColor: '#FAFAFA',
      layers: [
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'name',
          text: 'Your Name',
          x: 0.08,
          y: 0.14,
          width: 0.84,
          height: 0.1,
          zIndex: z++,
          fontFamily: 'playfair',
          fontSize: 0.075,
          color: '#111111',
          bold: true,
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'title',
          text: 'Creative Director',
          x: 0.1,
          y: 0.26,
          width: 0.8,
          height: 0.06,
          zIndex: z++,
          fontFamily: 'roboto',
          fontSize: 0.035,
          color: '#666666',
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.shape,
          x: 0.35,
          y: 0.35,
          width: 0.3,
          height: 0.006,
          zIndex: z++,
          color: '#111111',
          shape: 'rect',
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.qr,
          fieldKey: 'qr',
          qrData: 'https://tapni.com',
          qrColor: '#111111',
          x: 0.28,
          y: 0.42,
          width: 0.44,
          height: 0.28,
          zIndex: z++,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'email',
          text: 'hello@email.com',
          x: 0.1,
          y: 0.76,
          width: 0.8,
          height: 0.05,
          zIndex: z++,
          fontSize: 0.028,
          color: '#333333',
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'phone',
          text: '+1 234 567 890',
          x: 0.1,
          y: 0.84,
          width: 0.8,
          height: 0.05,
          zIndex: z++,
          fontSize: 0.028,
          color: '#333333',
          align: DesignTextAlign.center,
        ),
      ],
    );
  }

  static BusinessCardDesign _boldAccent() {
    final id = 'bc_bold';
    var z = 0;
    return BusinessCardDesign(
      templateId: id,
      category: 'modern',
      backgroundColor: '#111827',
      layers: [
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.shape,
          x: 0,
          y: 0.72,
          width: 1,
          height: 0.28,
          zIndex: z++,
          color: '#F59E0B',
          shape: 'rect',
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'name',
          text: 'Your Name',
          x: 0.08,
          y: 0.1,
          width: 0.84,
          height: 0.1,
          zIndex: z++,
          fontFamily: 'cairo',
          fontSize: 0.07,
          color: '#FFFFFF',
          bold: true,
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'title',
          text: 'Founder',
          x: 0.1,
          y: 0.22,
          width: 0.8,
          height: 0.06,
          zIndex: z++,
          fontSize: 0.036,
          color: '#F59E0B',
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.qr,
          fieldKey: 'qr',
          qrData: 'https://tapni.com',
          qrColor: '#111827',
          x: 0.28,
          y: 0.32,
          width: 0.44,
          height: 0.28,
          zIndex: z++,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'email',
          text: 'hello@email.com',
          x: 0.1,
          y: 0.8,
          width: 0.8,
          height: 0.06,
          zIndex: z++,
          fontSize: 0.03,
          color: '#111827',
          bold: true,
          align: DesignTextAlign.center,
        ),
      ],
    );
  }

  static BusinessCardDesign _darkElegant() {
    final id = 'bc_dark';
    var z = 0;
    return BusinessCardDesign(
      templateId: id,
      category: 'elegant',
      backgroundColor: '#1C1917',
      layers: [
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'company',
          text: 'COMPANY',
          x: 0.1,
          y: 0.08,
          width: 0.8,
          height: 0.05,
          zIndex: z++,
          fontFamily: 'cormorant',
          fontSize: 0.03,
          color: '#A8A29E',
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'name',
          text: 'Your Name',
          x: 0.08,
          y: 0.16,
          width: 0.84,
          height: 0.1,
          zIndex: z++,
          fontFamily: 'playfair',
          fontSize: 0.075,
          color: '#FAFAF9',
          bold: true,
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'title',
          text: 'Managing Partner',
          x: 0.1,
          y: 0.28,
          width: 0.8,
          height: 0.06,
          zIndex: z++,
          fontSize: 0.034,
          color: '#D6D3D1',
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.qr,
          fieldKey: 'qr',
          qrData: 'https://tapni.com',
          qrColor: '#1C1917',
          x: 0.28,
          y: 0.4,
          width: 0.44,
          height: 0.28,
          zIndex: z++,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'phone',
          text: '+1 234 567 890',
          x: 0.1,
          y: 0.78,
          width: 0.8,
          height: 0.05,
          zIndex: z++,
          fontSize: 0.028,
          color: '#A8A29E',
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'email',
          text: 'hello@email.com',
          x: 0.1,
          y: 0.86,
          width: 0.8,
          height: 0.05,
          zIndex: z++,
          fontSize: 0.028,
          color: '#A8A29E',
          align: DesignTextAlign.center,
        ),
      ],
    );
  }

  static BusinessCardDesign _splitHeader() {
    final id = 'bc_split';
    var z = 0;
    return BusinessCardDesign(
      templateId: id,
      category: 'modern',
      backgroundColor: '#FFFFFF',
      layers: [
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.shape,
          x: 0,
          y: 0,
          width: 1,
          height: 0.32,
          zIndex: z++,
          color: '#0EA5E9',
          shape: 'rect',
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'name',
          text: 'Your Name',
          x: 0.08,
          y: 0.1,
          width: 0.84,
          height: 0.1,
          zIndex: z++,
          fontFamily: 'cairo',
          fontSize: 0.065,
          color: '#FFFFFF',
          bold: true,
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'title',
          text: 'Product Designer',
          x: 0.1,
          y: 0.38,
          width: 0.8,
          height: 0.06,
          zIndex: z++,
          fontSize: 0.038,
          color: '#0F172A',
          bold: true,
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'company',
          text: 'Company Inc.',
          x: 0.1,
          y: 0.45,
          width: 0.8,
          height: 0.05,
          zIndex: z++,
          fontSize: 0.03,
          color: '#64748B',
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.qr,
          fieldKey: 'qr',
          qrData: 'https://tapni.com',
          qrColor: '#0F172A',
          x: 0.3,
          y: 0.54,
          width: 0.4,
          height: 0.25,
          zIndex: z++,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'email',
          text: 'hello@email.com',
          x: 0.1,
          y: 0.84,
          width: 0.8,
          height: 0.05,
          zIndex: z++,
          fontSize: 0.028,
          color: '#334155',
          align: DesignTextAlign.center,
        ),
      ],
    );
  }

  static BusinessCardDesign _qrFocus() {
    final id = 'bc_qr_focus';
    var z = 0;
    return BusinessCardDesign(
      templateId: id,
      category: 'qr',
      backgroundColor: '#F8FAFC',
      layers: [
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.qr,
          fieldKey: 'qr',
          qrData: 'https://tapni.com',
          qrColor: '#020617',
          x: 0.18,
          y: 0.1,
          width: 0.64,
          height: 0.42,
          zIndex: z++,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'name',
          text: 'Your Name',
          x: 0.08,
          y: 0.58,
          width: 0.84,
          height: 0.09,
          zIndex: z++,
          fontFamily: 'cairo',
          fontSize: 0.065,
          color: '#020617',
          bold: true,
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'title',
          text: 'Scan to connect',
          x: 0.1,
          y: 0.7,
          width: 0.8,
          height: 0.06,
          zIndex: z++,
          fontSize: 0.034,
          color: '#64748B',
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'email',
          text: 'hello@email.com',
          x: 0.1,
          y: 0.84,
          width: 0.8,
          height: 0.05,
          zIndex: z++,
          fontSize: 0.028,
          color: '#334155',
          align: DesignTextAlign.center,
        ),
      ],
    );
  }

  static BusinessCardDesign _coralSoft() {
    final id = 'bc_coral';
    var z = 0;
    return BusinessCardDesign(
      templateId: id,
      category: 'creative',
      backgroundColor: '#FFF7ED',
      layers: [
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.shape,
          x: 0.55,
          y: -0.08,
          width: 0.6,
          height: 0.35,
          zIndex: z++,
          color: '#FB923C',
          shape: 'circle',
          opacity: 0.35,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'name',
          text: 'Your Name',
          x: 0.08,
          y: 0.14,
          width: 0.84,
          height: 0.1,
          zIndex: z++,
          fontFamily: 'cairo',
          fontSize: 0.07,
          color: '#9A3412',
          bold: true,
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'title',
          text: 'Brand Strategist',
          x: 0.1,
          y: 0.26,
          width: 0.8,
          height: 0.06,
          zIndex: z++,
          fontSize: 0.035,
          color: '#C2410C',
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.qr,
          fieldKey: 'qr',
          qrData: 'https://tapni.com',
          qrColor: '#9A3412',
          x: 0.28,
          y: 0.38,
          width: 0.44,
          height: 0.28,
          zIndex: z++,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'website',
          text: 'www.yoursite.com',
          x: 0.1,
          y: 0.78,
          width: 0.8,
          height: 0.05,
          zIndex: z++,
          fontSize: 0.028,
          color: '#7C2D12',
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'phone',
          text: '+1 234 567 890',
          x: 0.1,
          y: 0.86,
          width: 0.8,
          height: 0.05,
          zIndex: z++,
          fontSize: 0.028,
          color: '#7C2D12',
          align: DesignTextAlign.center,
        ),
      ],
    );
  }

  static BusinessCardDesign _monoClean() {
    final id = 'bc_mono';
    var z = 0;
    return BusinessCardDesign(
      templateId: id,
      category: 'minimal',
      backgroundColor: '#FFFFFF',
      layers: [
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.shape,
          x: 0.04,
          y: 0.04,
          width: 0.92,
          height: 0.92,
          zIndex: z++,
          color: '#FFFFFF',
          shape: 'rect',
          opacity: 0,
          borderWidth: 0.01,
          borderColor: '#111111',
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'name',
          text: 'YOUR NAME',
          x: 0.1,
          y: 0.12,
          width: 0.8,
          height: 0.08,
          zIndex: z++,
          fontFamily: 'roboto',
          fontSize: 0.055,
          color: '#111111',
          bold: true,
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'title',
          text: 'TITLE / ROLE',
          x: 0.1,
          y: 0.22,
          width: 0.8,
          height: 0.06,
          zIndex: z++,
          fontSize: 0.03,
          color: '#111111',
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.shape,
          x: 0.2,
          y: 0.32,
          width: 0.6,
          height: 0.004,
          zIndex: z++,
          color: '#111111',
          shape: 'line',
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.qr,
          fieldKey: 'qr',
          qrData: 'https://tapni.com',
          qrColor: '#111111',
          x: 0.28,
          y: 0.38,
          width: 0.44,
          height: 0.28,
          zIndex: z++,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'email',
          text: 'hello@email.com',
          x: 0.1,
          y: 0.74,
          width: 0.8,
          height: 0.05,
          zIndex: z++,
          fontSize: 0.028,
          color: '#111111',
          align: DesignTextAlign.center,
        ),
        DesignLayer(
          id: _nid(id, z),
          type: DesignLayerType.text,
          fieldKey: 'phone',
          text: '+1 234 567 890',
          x: 0.1,
          y: 0.82,
          width: 0.8,
          height: 0.05,
          zIndex: z++,
          fontSize: 0.028,
          color: '#111111',
          align: DesignTextAlign.center,
        ),
      ],
    );
  }
}
