import 'package:tapni_app/models/invitation_design.dart';
import 'package:tapni_app/utils/country_dial_codes.dart';

/// Country / category invitation template catalog.
class InvitationTemplateCatalog {
  InvitationTemplateCatalog._();

  /// Markets with curated official templates — shown first in the country list.
  static const featuredCountryCodes = <String>[
    'SA',
    'AE',
    'KW',
    'QA',
    'BH',
    'OM',
    'PK',
    'IN',
    'TR',
    'EG',
    'US',
    'GB',
  ];

  /// All countries (from [kCountryDialCodes]), featured markets first.
  static List<Map<String, String>> get countries {
    final byIso = <String, CountryDialCode>{
      for (final c in kCountryDialCodes) c.iso.toUpperCase(): c,
    };
    final ordered = <CountryDialCode>[];
    final seen = <String>{};

    for (final code in featuredCountryCodes) {
      final c = byIso[code];
      if (c != null && seen.add(c.iso.toUpperCase())) ordered.add(c);
    }
    for (final c in kCountryDialCodes) {
      if (seen.add(c.iso.toUpperCase())) ordered.add(c);
    }

    return [
      for (final c in ordered)
        {
          'code': c.iso.toUpperCase(),
          'name': c.name,
          'flag': c.flagEmoji,
        },
    ];
  }

  /// Arabic / RTL locales for blank invitation defaults.
  static const rtlCountryCodes = <String>{
    'SA',
    'AE',
    'KW',
    'QA',
    'BH',
    'OM',
    'EG',
    'IQ',
    'JO',
    'LB',
    'SY',
    'YE',
    'LY',
    'TN',
    'DZ',
    'MA',
    'SD',
    'PS',
    'MR',
    'PK',
  };

  static bool isRtlCountry(String? code) {
    if (code == null || code.isEmpty) return false;
    return rtlCountryCodes.contains(code.toUpperCase());
  }

  static String defaultLocaleForCountry(String? code) {
    final upper = code?.toUpperCase();
    if (upper == 'PK') return 'ur';
    if (isRtlCountry(upper) && upper != 'PK') return 'ar';
    return 'en';
  }

  static const categories = <Map<String, String>>[
    {'id': 'wedding', 'name': 'Wedding', 'nameAr': 'زفاف', 'icon': 'favorite'},
    {
      'id': 'engagement',
      'name': 'Engagement',
      'nameAr': 'خطوبة',
      'icon': 'diamond',
    },
    {
      'id': 'birthday',
      'name': 'Birthday',
      'nameAr': 'عيد ميلاد',
      'icon': 'cake',
    },
    {
      'id': 'anniversary',
      'name': 'Anniversary',
      'nameAr': 'ذكرى',
      'icon': 'celebration',
    },
    {
      'id': 'baby_shower',
      'name': 'Baby Shower',
      'nameAr': 'مولود',
      'icon': 'child_care',
    },
    {
      'id': 'graduation',
      'name': 'Graduation',
      'nameAr': 'تخرج',
      'icon': 'school',
    },
    {
      'id': 'eid',
      'name': 'Eid / Eid Party',
      'nameAr': 'عيد',
      'icon': 'mosque',
    },
    {
      'id': 'business',
      'name': 'Business',
      'nameAr': 'عمل',
      'icon': 'business_center',
    },
    {'id': 'other', 'name': 'Other', 'nameAr': 'أخرى', 'icon': 'more_horiz'},
  ];

  static List<InvitationTemplate> get all => _templates;

  static List<InvitationTemplate> byCountry(String code) =>
      _templates.where((t) => t.countryCode == code).toList();

  static List<InvitationTemplate> filter({
    String? countryCode,
    String? category,
  }) {
    return _templates.where((t) {
      if (countryCode != null &&
          countryCode.isNotEmpty &&
          t.countryCode != countryCode) {
        return false;
      }
      if (category != null && category.isNotEmpty && t.category != category) {
        return false;
      }
      return true;
    }).toList();
  }

  static InvitationTemplate? byId(String id) {
    try {
      return _templates.firstWhere((t) => t.id == id);
    } catch (_) {
      return null;
    }
  }

  static final List<InvitationTemplate> _templates = [
    // ── Saudi Arabia ──────────────────────────────────────────────
    InvitationTemplate(
      id: 'sa_wedding_gold_black',
      name: 'Royal Gold & Black',
      nameAr: 'ذهبي ملكي',
      countryCode: 'SA',
      category: 'wedding',
      locale: 'ar',
      rtl: true,
      previewColor: '#0A0A0A',
      accentColor: '#D4AF37',
      build: _saWeddingGoldBlack,
    ),
    InvitationTemplate(
      id: 'sa_wedding_navy_teal',
      name: 'Navy Classic',
      nameAr: 'كحلي كلاسيك',
      countryCode: 'SA',
      category: 'wedding',
      locale: 'ar',
      rtl: true,
      previewColor: '#F5F2EB',
      accentColor: '#1B3A4B',
      build: _saWeddingNavy,
    ),
    InvitationTemplate(
      id: 'sa_wedding_soft_pink',
      name: 'Soft Rose Minimal',
      nameAr: 'وردي ناعم',
      countryCode: 'SA',
      category: 'wedding',
      locale: 'ar',
      rtl: true,
      previewColor: '#F7EDE8',
      accentColor: '#C08081',
      build: _saWeddingSoftPink,
    ),
    InvitationTemplate(
      id: 'sa_eid_green',
      name: 'Eid Emerald',
      nameAr: 'عيد زمردي',
      countryCode: 'SA',
      category: 'eid',
      locale: 'ar',
      rtl: true,
      previewColor: '#0B3D2E',
      accentColor: '#C9A227',
      build: _saEidEmerald,
    ),
    InvitationTemplate(
      id: 'sa_business_dark',
      name: 'Corporate Dark',
      nameAr: 'عمل داكن',
      countryCode: 'SA',
      category: 'business',
      locale: 'ar',
      rtl: true,
      previewColor: '#121212',
      accentColor: '#4FC3F7',
      build: _saBusinessDark,
    ),

    // ── UAE ───────────────────────────────────────────────────────
    InvitationTemplate(
      id: 'ae_wedding_luxury',
      name: 'Dubai Luxury',
      nameAr: 'دبي فاخر',
      countryCode: 'AE',
      category: 'wedding',
      locale: 'ar',
      rtl: true,
      previewColor: '#1A0A2E',
      accentColor: '#E8C547',
      build: _aeWeddingLuxury,
    ),
    InvitationTemplate(
      id: 'ae_business_modern',
      name: 'Modern Business',
      nameAr: 'عمل عصري',
      countryCode: 'AE',
      category: 'business',
      locale: 'en',
      rtl: false,
      previewColor: '#0D1B2A',
      accentColor: '#00B4D8',
      build: _aeBusinessModern,
    ),

    // ── Pakistan ──────────────────────────────────────────────────
    InvitationTemplate(
      id: 'pk_wedding_floral',
      name: 'Mehndi Floral',
      nameAr: 'مہندی فلورا',
      countryCode: 'PK',
      category: 'wedding',
      locale: 'ur',
      rtl: true,
      previewColor: '#3D0C11',
      accentColor: '#E8B4B8',
      build: _pkWeddingFloral,
    ),
    InvitationTemplate(
      id: 'pk_birthday_bright',
      name: 'Bright Birthday',
      nameAr: 'سالگرہ روشن',
      countryCode: 'PK',
      category: 'birthday',
      locale: 'ur',
      rtl: true,
      previewColor: '#FFF5F7',
      accentColor: '#E91E63',
      build: _pkBirthdayBright,
    ),

    // ── India ─────────────────────────────────────────────────────
    InvitationTemplate(
      id: 'in_wedding_marigold',
      name: 'Marigold Wedding',
      nameAr: 'زفاف هندي',
      countryCode: 'IN',
      category: 'wedding',
      locale: 'en',
      rtl: false,
      previewColor: '#1A0F00',
      accentColor: '#FF8C00',
      build: _inWeddingMarigold,
    ),

    // ── Turkey ────────────────────────────────────────────────────
    InvitationTemplate(
      id: 'tr_wedding_ottoman',
      name: 'Ottoman Elegance',
      nameAr: 'عثماني أنيق',
      countryCode: 'TR',
      category: 'wedding',
      locale: 'tr',
      rtl: false,
      previewColor: '#1C2833',
      accentColor: '#C0392B',
      build: _trWeddingOttoman,
    ),

    // ── Egypt ─────────────────────────────────────────────────────
    InvitationTemplate(
      id: 'eg_wedding_nile',
      name: 'Nile Gold',
      nameAr: 'ذهب النيل',
      countryCode: 'EG',
      category: 'wedding',
      locale: 'ar',
      rtl: true,
      previewColor: '#0C2340',
      accentColor: '#C9A84C',
      build: _egWeddingNile,
    ),

    // ── Western ───────────────────────────────────────────────────
    InvitationTemplate(
      id: 'us_wedding_minimal',
      name: 'Modern Minimal',
      nameAr: 'بسيط عصري',
      countryCode: 'US',
      category: 'wedding',
      locale: 'en',
      rtl: false,
      previewColor: '#FAFAFA',
      accentColor: '#212121',
      build: _usWeddingMinimal,
    ),
    InvitationTemplate(
      id: 'us_birthday_party',
      name: 'Party Pop',
      nameAr: 'حفلة',
      countryCode: 'US',
      category: 'birthday',
      locale: 'en',
      rtl: false,
      previewColor: '#6C63FF',
      accentColor: '#FFD93D',
      build: _usBirthdayParty,
    ),
    InvitationTemplate(
      id: 'gb_anniversary_classic',
      name: 'Classic Anniversary',
      nameAr: 'ذكرى كلاسيك',
      countryCode: 'GB',
      category: 'anniversary',
      locale: 'en',
      rtl: false,
      previewColor: '#F8F4EC',
      accentColor: '#8B4513',
      build: _gbAnniversary,
    ),
    InvitationTemplate(
      id: 'kw_engagement_pearl',
      name: 'Pearl Engagement',
      nameAr: 'خطوبة لؤلؤ',
      countryCode: 'KW',
      category: 'engagement',
      locale: 'ar',
      rtl: true,
      previewColor: '#F5F0E8',
      accentColor: '#5D4E6D',
      build: _kwEngagement,
    ),
    InvitationTemplate(
      id: 'qa_graduation_pride',
      name: 'Graduation Pride',
      nameAr: 'تخرج فخر',
      countryCode: 'QA',
      category: 'graduation',
      locale: 'ar',
      rtl: true,
      previewColor: '#8D1B3D',
      accentColor: '#FFFFFF',
      build: _qaGraduation,
    ),
  ];
}

// ─── Helpers ──────────────────────────────────────────────────────────────

DesignLayer _t({
  required String fieldKey,
  required String text,
  required String color,
  required double x,
  required double y,
  required double w,
  required double h,
  required int z,
  String font = 'cairo',
  double size = 0.04,
  bool bold = false,
  bool italic = false,
  DesignTextAlign align = DesignTextAlign.center,
}) {
  return DesignLayer(
    id: InvitationDesign.newId(),
    type: DesignLayerType.text,
    fieldKey: fieldKey,
    text: text,
    color: color,
    x: x,
    y: y,
    width: w,
    height: h,
    zIndex: z,
    fontFamily: font,
    fontSize: size,
    bold: bold,
    italic: italic,
    align: align,
  );
}

DesignLayer _iconField({
  required String fieldKey,
  required String text,
  required String icon,
  required String color,
  required double x,
  required double y,
  required double w,
  required double h,
  required int z,
  String font = 'cairo',
  double size = 0.028,
}) {
  return DesignLayer(
    id: InvitationDesign.newId(),
    type: DesignLayerType.iconField,
    fieldKey: fieldKey,
    text: text,
    iconName: icon,
    color: color,
    x: x,
    y: y,
    width: w,
    height: h,
    zIndex: z,
    fontFamily: font,
    fontSize: size,
    align: DesignTextAlign.center,
  );
}

DesignLayer _shape({
  required String shape,
  required String color,
  required double x,
  required double y,
  required double w,
  required double h,
  required int z,
  double opacity = 1,
  double borderWidth = 0,
  String borderColor = '#FFFFFF',
}) {
  return DesignLayer(
    id: InvitationDesign.newId(),
    type: DesignLayerType.shape,
    shape: shape,
    color: color,
    x: x,
    y: y,
    width: w,
    height: h,
    zIndex: z,
    opacity: opacity,
    borderWidth: borderWidth,
    borderColor: borderColor,
  );
}

DesignLayer _qr({
  required String color,
  required double x,
  required double y,
  required double size,
  required int z,
  String data = 'barqody://invitation/preview',
}) {
  return DesignLayer(
    id: InvitationDesign.newId(),
    type: DesignLayerType.qr,
    fieldKey: 'qr',
    qrData: data,
    qrColor: color,
    x: x,
    y: y,
    width: size,
    height: size,
    zIndex: z,
  );
}

DesignLayer _logoSlot({
  required double x,
  required double y,
  required double size,
  required int z,
  String color = '#D4AF37',
}) {
  return DesignLayer(
    id: InvitationDesign.newId(),
    type: DesignLayerType.logo,
    fieldKey: 'logo',
    text: 'LOGO',
    color: color,
    x: x,
    y: y,
    width: size,
    height: size,
    zIndex: z,
    borderWidth: 1.5,
    borderColor: color,
  );
}

// ─── Template builders ────────────────────────────────────────────────────

InvitationDesign _saWeddingGoldBlack() {
  const gold = '#D4AF37';
  return InvitationDesign(
    templateId: 'sa_wedding_gold_black',
    countryCode: 'SA',
    category: 'wedding',
    locale: 'ar',
    rtl: true,
    backgroundColor: '#0A0A0A',
    layers: [
      _shape(
        shape: 'rect',
        color: gold,
        x: 0.06,
        y: 0.04,
        w: 0.88,
        h: 0.92,
        z: 0,
        opacity: 0,
        borderWidth: 1.5,
        borderColor: gold,
      ),
      _logoSlot(x: 0.38, y: 0.06, size: 0.24, z: 1, color: gold),
      _t(
        fieldKey: 'greeting',
        text: 'يشرفني دعوتكم لحضور',
        color: gold,
        x: 0.1,
        y: 0.28,
        w: 0.8,
        h: 0.05,
        z: 2,
        size: 0.032,
        italic: true,
      ),
      _t(
        fieldKey: 'title',
        text: 'حفل زفافي',
        color: gold,
        x: 0.08,
        y: 0.34,
        w: 0.84,
        h: 0.1,
        z: 3,
        font: 'amiri',
        size: 0.085,
        bold: true,
      ),
      _t(
        fieldKey: 'message',
        text: 'على شرف وليمة العشاء مساء يوم',
        color: gold,
        x: 0.1,
        y: 0.45,
        w: 0.8,
        h: 0.05,
        z: 4,
        size: 0.03,
      ),
      _iconField(
        fieldKey: 'time',
        text: 'من 8:00 م\nإلى 12:00 ص',
        icon: 'clock',
        color: gold,
        x: 0.08,
        y: 0.52,
        w: 0.26,
        h: 0.12,
        z: 5,
      ),
      _iconField(
        fieldKey: 'venue',
        text: 'قاعة الاحتفال\nالرياض',
        icon: 'location',
        color: gold,
        x: 0.37,
        y: 0.52,
        w: 0.26,
        h: 0.12,
        z: 6,
      ),
      _iconField(
        fieldKey: 'date',
        text: 'الجمعة\n١٥ رجب ١٤٤٧',
        icon: 'calendar',
        color: gold,
        x: 0.66,
        y: 0.52,
        w: 0.26,
        h: 0.12,
        z: 7,
      ),
      _shape(
        shape: 'divider',
        color: gold,
        x: 0.2,
        y: 0.68,
        w: 0.6,
        h: 0.02,
        z: 8,
      ),
      _t(
        fieldKey: 'host_label',
        text: 'الداعي',
        color: gold,
        x: 0.2,
        y: 0.72,
        w: 0.6,
        h: 0.04,
        z: 9,
        size: 0.028,
      ),
      _t(
        fieldKey: 'host',
        text: 'اسم الداعي',
        color: gold,
        x: 0.15,
        y: 0.76,
        w: 0.7,
        h: 0.06,
        z: 10,
        font: 'amiri',
        size: 0.05,
        bold: true,
      ),
      _t(
        fieldKey: 'blessing',
        text: 'وبارك الله لكما وبارك عليكما',
        color: gold,
        x: 0.1,
        y: 0.86,
        w: 0.8,
        h: 0.05,
        z: 11,
        font: 'amiri',
        size: 0.03,
        italic: true,
      ),
    ],
  );
}

InvitationDesign _saWeddingNavy() {
  const navy = '#1B3A4B';
  const teal = '#2A9D8F';
  return InvitationDesign(
    templateId: 'sa_wedding_navy_teal',
    countryCode: 'SA',
    category: 'wedding',
    locale: 'ar',
    rtl: true,
    backgroundColor: '#F5F2EB',
    layers: [
      _t(
        fieldKey: 'header',
        text: 'دعوة زفاف',
        color: navy,
        x: 0.1,
        y: 0.06,
        w: 0.8,
        h: 0.1,
        z: 1,
        font: 'amiri',
        size: 0.09,
        bold: true,
      ),
      _t(
        fieldKey: 'greeting',
        text: 'بكل مشاعر الحب والسرور ندعوكم لحضور',
        color: navy,
        x: 0.1,
        y: 0.2,
        w: 0.8,
        h: 0.05,
        z: 2,
        size: 0.03,
      ),
      _t(
        fieldKey: 'title',
        text: 'حفل زفاف',
        color: teal,
        x: 0.1,
        y: 0.28,
        w: 0.8,
        h: 0.08,
        z: 3,
        font: 'cairo',
        size: 0.07,
        bold: true,
      ),
      _t(
        fieldKey: 'names',
        text: 'العريس  ♥  العروس',
        color: teal,
        x: 0.1,
        y: 0.38,
        w: 0.8,
        h: 0.07,
        z: 4,
        size: 0.05,
        bold: true,
      ),
      _t(
        fieldKey: 'message',
        text: 'على شرف وليمة العشاء',
        color: navy,
        x: 0.15,
        y: 0.47,
        w: 0.7,
        h: 0.04,
        z: 5,
        size: 0.03,
      ),
      _iconField(
        fieldKey: 'date',
        text: 'السبت\n١٧ / ٥ / ١٤٤٧ هـ\n٩ / ١١ / ٢٠٢٥ م',
        icon: 'calendar',
        color: navy,
        x: 0.52,
        y: 0.54,
        w: 0.38,
        h: 0.16,
        z: 6,
      ),
      _iconField(
        fieldKey: 'venue',
        text: 'الرياض\nقاعة السلام',
        icon: 'location',
        color: navy,
        x: 0.1,
        y: 0.54,
        w: 0.38,
        h: 0.16,
        z: 7,
      ),
      _shape(
        shape: 'line',
        color: navy,
        x: 0.49,
        y: 0.55,
        w: 0.02,
        h: 0.14,
        z: 5,
      ),
      _t(
        fieldKey: 'host',
        text: 'بدعوة من العائلة',
        color: navy,
        x: 0.15,
        y: 0.74,
        w: 0.7,
        h: 0.05,
        z: 8,
        size: 0.032,
      ),
      _t(
        fieldKey: 'blessing',
        text: 'وبارك الله لكما وبارك عليكما',
        color: navy,
        x: 0.1,
        y: 0.82,
        w: 0.8,
        h: 0.05,
        z: 9,
        font: 'amiri',
        size: 0.032,
        italic: true,
      ),
      _shape(
        shape: 'rect',
        color: navy,
        x: 0,
        y: 0.92,
        w: 1,
        h: 0.08,
        z: 10,
        opacity: 0.85,
      ),
    ],
  );
}

InvitationDesign _saWeddingSoftPink() {
  const rose = '#C08081';
  const dark = '#5C4033';
  return InvitationDesign(
    templateId: 'sa_wedding_soft_pink',
    countryCode: 'SA',
    category: 'wedding',
    locale: 'ar',
    rtl: true,
    backgroundColor: '#F7EDE8',
    layers: [
      _logoSlot(x: 0.08, y: 0.04, size: 0.14, z: 1, color: rose),
      _t(
        fieldKey: 'header',
        text: 'بطاقة دعوة',
        color: dark,
        x: 0.25,
        y: 0.05,
        w: 0.6,
        h: 0.04,
        z: 2,
        size: 0.028,
      ),
      _t(
        fieldKey: 'title',
        text: 'حفل الزفاف',
        color: dark,
        x: 0.1,
        y: 0.12,
        w: 0.8,
        h: 0.1,
        z: 3,
        font: 'amiri',
        size: 0.08,
        bold: true,
      ),
      _iconField(
        fieldKey: 'date',
        text: '18.07.2026',
        icon: 'calendar',
        color: dark,
        x: 0.08,
        y: 0.28,
        w: 0.26,
        h: 0.1,
        z: 4,
      ),
      _iconField(
        fieldKey: 'venue',
        text: 'قاعة بين النخيل',
        icon: 'location',
        color: dark,
        x: 0.37,
        y: 0.28,
        w: 0.26,
        h: 0.1,
        z: 5,
      ),
      _iconField(
        fieldKey: 'time',
        text: '9:00 م',
        icon: 'clock',
        color: dark,
        x: 0.66,
        y: 0.28,
        w: 0.26,
        h: 0.1,
        z: 6,
      ),
      _qr(color: rose, x: 0.35, y: 0.42, size: 0.3, z: 7),
      _t(
        fieldKey: 'message',
        text: 'نرجو الحضور في الموعد المحدد',
        color: dark,
        x: 0.1,
        y: 0.76,
        w: 0.8,
        h: 0.05,
        z: 8,
        size: 0.028,
      ),
      _t(
        fieldKey: 'host',
        text: 'MY INVITE',
        color: rose,
        x: 0.2,
        y: 0.88,
        w: 0.6,
        h: 0.04,
        z: 9,
        size: 0.025,
        bold: true,
      ),
    ],
  );
}

InvitationDesign _saEidEmerald() {
  const gold = '#C9A227';
  return InvitationDesign(
    templateId: 'sa_eid_green',
    countryCode: 'SA',
    category: 'eid',
    locale: 'ar',
    rtl: true,
    backgroundColor: '#0B3D2E',
    layers: [
      _t(
        fieldKey: 'title',
        text: 'عيد مبارك',
        color: gold,
        x: 0.1,
        y: 0.2,
        w: 0.8,
        h: 0.12,
        z: 1,
        font: 'amiri',
        size: 0.1,
        bold: true,
      ),
      _t(
        fieldKey: 'message',
        text: 'كل عام وأنتم بخير\nيسعدنا دعوتكم لحضور حفل العيد',
        color: '#FFFFFF',
        x: 0.1,
        y: 0.38,
        w: 0.8,
        h: 0.12,
        z: 2,
        size: 0.035,
      ),
      _iconField(
        fieldKey: 'date',
        text: 'يوم العيد',
        icon: 'calendar',
        color: gold,
        x: 0.15,
        y: 0.55,
        w: 0.3,
        h: 0.1,
        z: 3,
      ),
      _iconField(
        fieldKey: 'venue',
        text: 'منزل العائلة',
        icon: 'location',
        color: gold,
        x: 0.55,
        y: 0.55,
        w: 0.3,
        h: 0.1,
        z: 4,
      ),
      _t(
        fieldKey: 'host',
        text: 'العائلة',
        color: gold,
        x: 0.2,
        y: 0.75,
        w: 0.6,
        h: 0.06,
        z: 5,
        size: 0.04,
        bold: true,
      ),
    ],
  );
}

InvitationDesign _saBusinessDark() {
  return InvitationDesign(
    templateId: 'sa_business_dark',
    countryCode: 'SA',
    category: 'business',
    locale: 'ar',
    rtl: true,
    backgroundColor: '#121212',
    layers: [
      _logoSlot(x: 0.38, y: 0.08, size: 0.24, z: 1, color: '#4FC3F7'),
      _t(
        fieldKey: 'title',
        text: 'دعوة اجتماع',
        color: '#FFFFFF',
        x: 0.1,
        y: 0.35,
        w: 0.8,
        h: 0.08,
        z: 2,
        size: 0.06,
        bold: true,
      ),
      _t(
        fieldKey: 'message',
        text: 'يسعدنا دعوتكم لحضور الاجتماع',
        color: '#B0BEC5',
        x: 0.1,
        y: 0.45,
        w: 0.8,
        h: 0.05,
        z: 3,
        size: 0.032,
      ),
      _iconField(
        fieldKey: 'date',
        text: 'التاريخ',
        icon: 'calendar',
        color: '#4FC3F7',
        x: 0.1,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 4,
      ),
      _iconField(
        fieldKey: 'time',
        text: 'الوقت',
        icon: 'clock',
        color: '#4FC3F7',
        x: 0.55,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 5,
      ),
      _iconField(
        fieldKey: 'venue',
        text: 'المكان',
        icon: 'location',
        color: '#4FC3F7',
        x: 0.2,
        y: 0.7,
        w: 0.6,
        h: 0.1,
        z: 6,
      ),
    ],
  );
}

InvitationDesign _aeWeddingLuxury() {
  const gold = '#E8C547';
  return InvitationDesign(
    templateId: 'ae_wedding_luxury',
    countryCode: 'AE',
    category: 'wedding',
    locale: 'ar',
    rtl: true,
    backgroundColor: '#1A0A2E',
    layers: [
      _t(
        fieldKey: 'title',
        text: 'حفل الزفاف',
        color: gold,
        x: 0.1,
        y: 0.25,
        w: 0.8,
        h: 0.1,
        z: 1,
        font: 'amiri',
        size: 0.09,
        bold: true,
      ),
      _t(
        fieldKey: 'names',
        text: 'العريس & العروس',
        color: '#FFFFFF',
        x: 0.1,
        y: 0.4,
        w: 0.8,
        h: 0.07,
        z: 2,
        size: 0.05,
      ),
      _iconField(
        fieldKey: 'date',
        text: 'التاريخ',
        icon: 'calendar',
        color: gold,
        x: 0.1,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 3,
      ),
      _iconField(
        fieldKey: 'venue',
        text: 'دبي',
        icon: 'location',
        color: gold,
        x: 0.55,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 4,
      ),
      _t(
        fieldKey: 'host',
        text: 'عائلة العريس',
        color: gold,
        x: 0.2,
        y: 0.75,
        w: 0.6,
        h: 0.05,
        z: 5,
        size: 0.035,
      ),
    ],
  );
}

InvitationDesign _aeBusinessModern() {
  return InvitationDesign(
    templateId: 'ae_business_modern',
    countryCode: 'AE',
    category: 'business',
    locale: 'en',
    rtl: false,
    backgroundColor: '#0D1B2A',
    layers: [
      _logoSlot(x: 0.38, y: 0.08, size: 0.24, z: 1, color: '#00B4D8'),
      _t(
        fieldKey: 'title',
        text: 'You\'re Invited',
        color: '#FFFFFF',
        x: 0.1,
        y: 0.35,
        w: 0.8,
        h: 0.08,
        z: 2,
        font: 'playfair',
        size: 0.06,
        bold: true,
      ),
      _t(
        fieldKey: 'message',
        text: 'Join us for an exclusive business event',
        color: '#90E0EF',
        x: 0.1,
        y: 0.45,
        w: 0.8,
        h: 0.05,
        z: 3,
        font: 'roboto',
        size: 0.03,
      ),
      _iconField(
        fieldKey: 'date',
        text: 'Date',
        icon: 'calendar',
        color: '#00B4D8',
        x: 0.1,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 4,
        font: 'roboto',
      ),
      _iconField(
        fieldKey: 'venue',
        text: 'Dubai',
        icon: 'location',
        color: '#00B4D8',
        x: 0.55,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 5,
        font: 'roboto',
      ),
    ],
  );
}

InvitationDesign _pkWeddingFloral() {
  const pink = '#E8B4B8';
  return InvitationDesign(
    templateId: 'pk_wedding_floral',
    countryCode: 'PK',
    category: 'wedding',
    locale: 'ur',
    rtl: true,
    backgroundColor: '#3D0C11',
    layers: [
      _t(
        fieldKey: 'title',
        text: 'شادی کی دعوت',
        color: pink,
        x: 0.1,
        y: 0.2,
        w: 0.8,
        h: 0.1,
        z: 1,
        font: 'amiri',
        size: 0.08,
        bold: true,
      ),
      _t(
        fieldKey: 'names',
        text: 'دولہا  ♥  دلہن',
        color: '#FFFFFF',
        x: 0.1,
        y: 0.35,
        w: 0.8,
        h: 0.07,
        z: 2,
        size: 0.05,
      ),
      _iconField(
        fieldKey: 'date',
        text: 'تاریخ',
        icon: 'calendar',
        color: pink,
        x: 0.1,
        y: 0.5,
        w: 0.35,
        h: 0.1,
        z: 3,
      ),
      _iconField(
        fieldKey: 'venue',
        text: 'لاہور',
        icon: 'location',
        color: pink,
        x: 0.55,
        y: 0.5,
        w: 0.35,
        h: 0.1,
        z: 4,
      ),
      _t(
        fieldKey: 'host',
        text: 'خاندان کی طرف سے',
        color: pink,
        x: 0.15,
        y: 0.7,
        w: 0.7,
        h: 0.05,
        z: 5,
        size: 0.032,
      ),
    ],
  );
}

InvitationDesign _pkBirthdayBright() {
  return InvitationDesign(
    templateId: 'pk_birthday_bright',
    countryCode: 'PK',
    category: 'birthday',
    locale: 'ur',
    rtl: true,
    backgroundColor: '#FFF5F7',
    layers: [
      _t(
        fieldKey: 'title',
        text: 'سالگرہ مبارک',
        color: '#E91E63',
        x: 0.1,
        y: 0.25,
        w: 0.8,
        h: 0.1,
        z: 1,
        size: 0.07,
        bold: true,
      ),
      _t(
        fieldKey: 'message',
        text: 'آپ کو دعوت ہے',
        color: '#880E4F',
        x: 0.15,
        y: 0.4,
        w: 0.7,
        h: 0.05,
        z: 2,
        size: 0.035,
      ),
      _iconField(
        fieldKey: 'date',
        text: 'تاریخ',
        icon: 'calendar',
        color: '#E91E63',
        x: 0.1,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 3,
      ),
      _iconField(
        fieldKey: 'time',
        text: 'وقت',
        icon: 'clock',
        color: '#E91E63',
        x: 0.55,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 4,
      ),
    ],
  );
}

InvitationDesign _inWeddingMarigold() {
  const orange = '#FF8C00';
  return InvitationDesign(
    templateId: 'in_wedding_marigold',
    countryCode: 'IN',
    category: 'wedding',
    locale: 'en',
    rtl: false,
    backgroundColor: '#1A0F00',
    layers: [
      _t(
        fieldKey: 'title',
        text: 'Wedding Invitation',
        color: orange,
        x: 0.08,
        y: 0.2,
        w: 0.84,
        h: 0.08,
        z: 1,
        font: 'playfair',
        size: 0.055,
        bold: true,
      ),
      _t(
        fieldKey: 'names',
        text: 'Bride  &  Groom',
        color: '#FFFFFF',
        x: 0.1,
        y: 0.35,
        w: 0.8,
        h: 0.08,
        z: 2,
        font: 'playfair',
        size: 0.055,
      ),
      _iconField(
        fieldKey: 'date',
        text: 'Date',
        icon: 'calendar',
        color: orange,
        x: 0.1,
        y: 0.5,
        w: 0.35,
        h: 0.1,
        z: 3,
        font: 'roboto',
      ),
      _iconField(
        fieldKey: 'venue',
        text: 'Venue',
        icon: 'location',
        color: orange,
        x: 0.55,
        y: 0.5,
        w: 0.35,
        h: 0.1,
        z: 4,
        font: 'roboto',
      ),
      _t(
        fieldKey: 'host',
        text: 'With love from the family',
        color: orange,
        x: 0.1,
        y: 0.7,
        w: 0.8,
        h: 0.05,
        z: 5,
        font: 'cormorant',
        size: 0.032,
        italic: true,
      ),
    ],
  );
}

InvitationDesign _trWeddingOttoman() {
  return InvitationDesign(
    templateId: 'tr_wedding_ottoman',
    countryCode: 'TR',
    category: 'wedding',
    locale: 'tr',
    rtl: false,
    backgroundColor: '#1C2833',
    layers: [
      _t(
        fieldKey: 'title',
        text: 'Düğün Davetiyesi',
        color: '#C0392B',
        x: 0.1,
        y: 0.25,
        w: 0.8,
        h: 0.08,
        z: 1,
        font: 'playfair',
        size: 0.055,
        bold: true,
      ),
      _t(
        fieldKey: 'names',
        text: 'Damat  &  Gelin',
        color: '#FFFFFF',
        x: 0.1,
        y: 0.4,
        w: 0.8,
        h: 0.07,
        z: 2,
        font: 'playfair',
        size: 0.05,
      ),
      _iconField(
        fieldKey: 'date',
        text: 'Tarih',
        icon: 'calendar',
        color: '#C0392B',
        x: 0.1,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 3,
        font: 'roboto',
      ),
      _iconField(
        fieldKey: 'venue',
        text: 'İstanbul',
        icon: 'location',
        color: '#C0392B',
        x: 0.55,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 4,
        font: 'roboto',
      ),
    ],
  );
}

InvitationDesign _egWeddingNile() {
  const gold = '#C9A84C';
  return InvitationDesign(
    templateId: 'eg_wedding_nile',
    countryCode: 'EG',
    category: 'wedding',
    locale: 'ar',
    rtl: true,
    backgroundColor: '#0C2340',
    layers: [
      _t(
        fieldKey: 'title',
        text: 'دعوة زفاف',
        color: gold,
        x: 0.1,
        y: 0.25,
        w: 0.8,
        h: 0.1,
        z: 1,
        font: 'amiri',
        size: 0.085,
        bold: true,
      ),
      _t(
        fieldKey: 'names',
        text: 'العريس و العروس',
        color: '#FFFFFF',
        x: 0.1,
        y: 0.4,
        w: 0.8,
        h: 0.07,
        z: 2,
        size: 0.045,
      ),
      _iconField(
        fieldKey: 'date',
        text: 'التاريخ',
        icon: 'calendar',
        color: gold,
        x: 0.1,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 3,
      ),
      _iconField(
        fieldKey: 'venue',
        text: 'القاهرة',
        icon: 'location',
        color: gold,
        x: 0.55,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 4,
      ),
    ],
  );
}

InvitationDesign _usWeddingMinimal() {
  return InvitationDesign(
    templateId: 'us_wedding_minimal',
    countryCode: 'US',
    category: 'wedding',
    locale: 'en',
    rtl: false,
    backgroundColor: '#FAFAFA',
    layers: [
      _t(
        fieldKey: 'header',
        text: 'TOGETHER WITH THEIR FAMILIES',
        color: '#757575',
        x: 0.08,
        y: 0.15,
        w: 0.84,
        h: 0.04,
        z: 1,
        font: 'roboto',
        size: 0.022,
      ),
      _t(
        fieldKey: 'names',
        text: 'Alex  &  Jordan',
        color: '#212121',
        x: 0.08,
        y: 0.28,
        w: 0.84,
        h: 0.1,
        z: 2,
        font: 'playfair',
        size: 0.07,
        bold: true,
      ),
      _t(
        fieldKey: 'title',
        text: 'request the pleasure of your company',
        color: '#616161',
        x: 0.1,
        y: 0.42,
        w: 0.8,
        h: 0.05,
        z: 3,
        font: 'cormorant',
        size: 0.032,
        italic: true,
      ),
      _shape(
        shape: 'divider',
        color: '#212121',
        x: 0.35,
        y: 0.5,
        w: 0.3,
        h: 0.02,
        z: 4,
      ),
      _iconField(
        fieldKey: 'date',
        text: 'Saturday, June 14',
        icon: 'calendar',
        color: '#212121',
        x: 0.15,
        y: 0.55,
        w: 0.7,
        h: 0.08,
        z: 5,
        font: 'roboto',
      ),
      _iconField(
        fieldKey: 'venue',
        text: 'The Grand Hall, NYC',
        icon: 'location',
        color: '#212121',
        x: 0.15,
        y: 0.65,
        w: 0.7,
        h: 0.08,
        z: 6,
        font: 'roboto',
      ),
    ],
  );
}

InvitationDesign _usBirthdayParty() {
  return InvitationDesign(
    templateId: 'us_birthday_party',
    countryCode: 'US',
    category: 'birthday',
    locale: 'en',
    rtl: false,
    backgroundColor: '#6C63FF',
    layers: [
      _t(
        fieldKey: 'title',
        text: 'Birthday Bash!',
        color: '#FFD93D',
        x: 0.08,
        y: 0.25,
        w: 0.84,
        h: 0.1,
        z: 1,
        font: 'playfair',
        size: 0.07,
        bold: true,
      ),
      _t(
        fieldKey: 'message',
        text: 'Come celebrate with us',
        color: '#FFFFFF',
        x: 0.1,
        y: 0.4,
        w: 0.8,
        h: 0.05,
        z: 2,
        font: 'roboto',
        size: 0.035,
      ),
      _iconField(
        fieldKey: 'date',
        text: 'Date',
        icon: 'calendar',
        color: '#FFD93D',
        x: 0.1,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 3,
        font: 'roboto',
      ),
      _iconField(
        fieldKey: 'time',
        text: '7 PM',
        icon: 'clock',
        color: '#FFD93D',
        x: 0.55,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 4,
        font: 'roboto',
      ),
    ],
  );
}

InvitationDesign _gbAnniversary() {
  return InvitationDesign(
    templateId: 'gb_anniversary_classic',
    countryCode: 'GB',
    category: 'anniversary',
    locale: 'en',
    rtl: false,
    backgroundColor: '#F8F4EC',
    layers: [
      _t(
        fieldKey: 'title',
        text: 'Anniversary Dinner',
        color: '#8B4513',
        x: 0.08,
        y: 0.25,
        w: 0.84,
        h: 0.1,
        z: 1,
        font: 'playfair',
        size: 0.06,
        bold: true,
      ),
      _t(
        fieldKey: 'message',
        text: 'Celebrating years of love',
        color: '#5D4037',
        x: 0.1,
        y: 0.4,
        w: 0.8,
        h: 0.05,
        z: 2,
        font: 'cormorant',
        size: 0.035,
        italic: true,
      ),
      _iconField(
        fieldKey: 'date',
        text: 'Date',
        icon: 'calendar',
        color: '#8B4513',
        x: 0.1,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 3,
        font: 'roboto',
      ),
      _iconField(
        fieldKey: 'venue',
        text: 'London',
        icon: 'location',
        color: '#8B4513',
        x: 0.55,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 4,
        font: 'roboto',
      ),
    ],
  );
}

InvitationDesign _kwEngagement() {
  return InvitationDesign(
    templateId: 'kw_engagement_pearl',
    countryCode: 'KW',
    category: 'engagement',
    locale: 'ar',
    rtl: true,
    backgroundColor: '#F5F0E8',
    layers: [
      _t(
        fieldKey: 'title',
        text: 'حفل خطوبة',
        color: '#5D4E6D',
        x: 0.1,
        y: 0.25,
        w: 0.8,
        h: 0.1,
        z: 1,
        font: 'amiri',
        size: 0.085,
        bold: true,
      ),
      _t(
        fieldKey: 'names',
        text: 'العريس و العروس',
        color: '#5D4E6D',
        x: 0.1,
        y: 0.4,
        w: 0.8,
        h: 0.07,
        z: 2,
        size: 0.045,
      ),
      _iconField(
        fieldKey: 'date',
        text: 'التاريخ',
        icon: 'calendar',
        color: '#5D4E6D',
        x: 0.1,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 3,
      ),
      _iconField(
        fieldKey: 'venue',
        text: 'الكويت',
        icon: 'location',
        color: '#5D4E6D',
        x: 0.55,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 4,
      ),
    ],
  );
}

InvitationDesign _qaGraduation() {
  return InvitationDesign(
    templateId: 'qa_graduation_pride',
    countryCode: 'QA',
    category: 'graduation',
    locale: 'ar',
    rtl: true,
    backgroundColor: '#8D1B3D',
    layers: [
      _t(
        fieldKey: 'title',
        text: 'حفل التخرج',
        color: '#FFFFFF',
        x: 0.1,
        y: 0.25,
        w: 0.8,
        h: 0.1,
        z: 1,
        font: 'amiri',
        size: 0.085,
        bold: true,
      ),
      _t(
        fieldKey: 'names',
        text: 'اسم الخريج',
        color: '#FFFFFF',
        x: 0.1,
        y: 0.4,
        w: 0.8,
        h: 0.07,
        z: 2,
        size: 0.05,
        bold: true,
      ),
      _iconField(
        fieldKey: 'date',
        text: 'التاريخ',
        icon: 'calendar',
        color: '#FFFFFF',
        x: 0.1,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 3,
      ),
      _iconField(
        fieldKey: 'venue',
        text: 'الدوحة',
        icon: 'location',
        color: '#FFFFFF',
        x: 0.55,
        y: 0.55,
        w: 0.35,
        h: 0.1,
        z: 4,
      ),
    ],
  );
}
