import 'package:intl/intl.dart';

/// Default when business/order has no currency (legacy PKR UI).
const String kDefaultCurrency = 'PKR';

/// ISO 3166-1 alpha-2 → ISO 4217 (mirrors backend currencies.js).
const Map<String, String> kIsoToCurrency = {
  'af': 'AFN',
  'al': 'ALL',
  'dz': 'DZD',
  'ad': 'EUR',
  'ao': 'AOA',
  'ag': 'XCD',
  'ar': 'ARS',
  'am': 'AMD',
  'au': 'AUD',
  'at': 'EUR',
  'az': 'AZN',
  'bs': 'BSD',
  'bh': 'BHD',
  'bd': 'BDT',
  'bb': 'BBD',
  'by': 'BYN',
  'be': 'EUR',
  'bz': 'BZD',
  'bj': 'XOF',
  'bt': 'BTN',
  'bo': 'BOB',
  'ba': 'BAM',
  'bw': 'BWP',
  'br': 'BRL',
  'bn': 'BND',
  'bg': 'BGN',
  'bf': 'XOF',
  'bi': 'BIF',
  'cv': 'CVE',
  'kh': 'KHR',
  'cm': 'XAF',
  'ca': 'CAD',
  'cf': 'XAF',
  'td': 'XAF',
  'cl': 'CLP',
  'cn': 'CNY',
  'co': 'COP',
  'km': 'KMF',
  'cg': 'XAF',
  'cr': 'CRC',
  'ci': 'XOF',
  'hr': 'EUR',
  'cu': 'CUP',
  'cy': 'EUR',
  'cz': 'CZK',
  'cd': 'CDF',
  'dk': 'DKK',
  'dj': 'DJF',
  'dm': 'XCD',
  'do': 'DOP',
  'ec': 'USD',
  'eg': 'EGP',
  'sv': 'USD',
  'gq': 'XAF',
  'er': 'ERN',
  'ee': 'EUR',
  'sz': 'SZL',
  'et': 'ETB',
  'fj': 'FJD',
  'fi': 'EUR',
  'fr': 'EUR',
  'ga': 'XAF',
  'gm': 'GMD',
  'ge': 'GEL',
  'de': 'EUR',
  'gh': 'GHS',
  'gr': 'EUR',
  'gd': 'XCD',
  'gt': 'GTQ',
  'gn': 'GNF',
  'gw': 'XOF',
  'gy': 'GYD',
  'ht': 'HTG',
  'va': 'EUR',
  'hn': 'HNL',
  'hu': 'HUF',
  'is': 'ISK',
  'in': 'INR',
  'id': 'IDR',
  'ir': 'IRR',
  'iq': 'IQD',
  'ie': 'EUR',
  'it': 'EUR',
  'jm': 'JMD',
  'jp': 'JPY',
  'jo': 'JOD',
  'kz': 'KZT',
  'ke': 'KES',
  'ki': 'AUD',
  'kw': 'KWD',
  'kg': 'KGS',
  'la': 'LAK',
  'lv': 'EUR',
  'lb': 'LBP',
  'ls': 'LSL',
  'lr': 'LRD',
  'ly': 'LYD',
  'li': 'CHF',
  'lt': 'EUR',
  'lu': 'EUR',
  'mg': 'MGA',
  'mw': 'MWK',
  'my': 'MYR',
  'mv': 'MVR',
  'ml': 'XOF',
  'mt': 'EUR',
  'mh': 'USD',
  'mr': 'MRU',
  'mu': 'MUR',
  'mx': 'MXN',
  'fm': 'USD',
  'md': 'MDL',
  'mc': 'EUR',
  'mn': 'MNT',
  'me': 'EUR',
  'ma': 'MAD',
  'mz': 'MZN',
  'mm': 'MMK',
  'na': 'NAD',
  'nr': 'AUD',
  'np': 'NPR',
  'nl': 'EUR',
  'nz': 'NZD',
  'ni': 'NIO',
  'ne': 'XOF',
  'ng': 'NGN',
  'kp': 'KPW',
  'mk': 'MKD',
  'no': 'NOK',
  'om': 'OMR',
  'pk': 'PKR',
  'pw': 'USD',
  'ps': 'ILS',
  'pa': 'USD',
  'pg': 'PGK',
  'py': 'PYG',
  'pe': 'PEN',
  'ph': 'PHP',
  'pl': 'PLN',
  'pt': 'EUR',
  'qa': 'QAR',
  'ro': 'RON',
  'ru': 'RUB',
  'rw': 'RWF',
  'kn': 'XCD',
  'lc': 'XCD',
  'vc': 'XCD',
  'ws': 'WST',
  'sm': 'EUR',
  'st': 'STN',
  'sa': 'SAR',
  'sn': 'XOF',
  'rs': 'RSD',
  'sc': 'SCR',
  'sl': 'SLE',
  'sg': 'SGD',
  'sk': 'EUR',
  'si': 'EUR',
  'sb': 'SBD',
  'so': 'SOS',
  'za': 'ZAR',
  'kr': 'KRW',
  'ss': 'SSP',
  'es': 'EUR',
  'lk': 'LKR',
  'sd': 'SDG',
  'sr': 'SRD',
  'se': 'SEK',
  'ch': 'CHF',
  'sy': 'SYP',
  'tw': 'TWD',
  'tj': 'TJS',
  'tz': 'TZS',
  'th': 'THB',
  'tl': 'USD',
  'tg': 'XOF',
  'to': 'TOP',
  'tt': 'TTD',
  'tn': 'TND',
  'tr': 'TRY',
  'tm': 'TMT',
  'tv': 'AUD',
  'ug': 'UGX',
  'ua': 'UAH',
  'ae': 'AED',
  'gb': 'GBP',
  'us': 'USD',
  'uy': 'UYU',
  'uz': 'UZS',
  'vu': 'VUV',
  've': 'VES',
  'vn': 'VND',
  'ye': 'YER',
  'zm': 'ZMW',
  'zw': 'ZWL',
};

/// Prefer familiar short labels for common markets (esp. PKR → Rs).
const Map<String, String> kCurrencySymbols = {
  'PKR': 'Rs',
  'INR': '₹',
  'USD': '\$',
  'EUR': '€',
  'GBP': '£',
  'AED': 'AED',
  'SAR': 'SAR',
  'TRY': '₺',
  'BDT': '৳',
  'AFN': '؋',
};

String normalizeCurrencyCode(String? value) {
  final code = (value ?? '').trim().toUpperCase();
  if (code.length == 3) return code;
  return '';
}

String currencyFromCountryName(String? country) {
  final key = (country ?? '').trim().toLowerCase();
  if (key.isEmpty) return kDefaultCurrency;
  if (key.length == 2) {
    return kIsoToCurrency[key] ?? kDefaultCurrency;
  }
  return kCountryNameToCurrency[key] ?? kDefaultCurrency;
}

/// Country display name (lowercase) → ISO 4217. Mirrors backend countries + currencies.
const Map<String, String> kCountryNameToCurrency = {
  'afghanistan': 'AFN',
  'albania': 'ALL',
  'algeria': 'DZD',
  'andorra': 'EUR',
  'angola': 'AOA',
  'antigua and barbuda': 'XCD',
  'argentina': 'ARS',
  'armenia': 'AMD',
  'australia': 'AUD',
  'austria': 'EUR',
  'azerbaijan': 'AZN',
  'bahamas': 'BSD',
  'bahrain': 'BHD',
  'bangladesh': 'BDT',
  'barbados': 'BBD',
  'belarus': 'BYN',
  'belgium': 'EUR',
  'belize': 'BZD',
  'benin': 'XOF',
  'bhutan': 'BTN',
  'bolivia': 'BOB',
  'bosnia and herzegovina': 'BAM',
  'botswana': 'BWP',
  'brazil': 'BRL',
  'brunei': 'BND',
  'bulgaria': 'BGN',
  'burkina faso': 'XOF',
  'burundi': 'BIF',
  'cabo verde': 'CVE',
  'cambodia': 'KHR',
  'cameroon': 'XAF',
  'canada': 'CAD',
  'central african republic': 'XAF',
  'chad': 'XAF',
  'chile': 'CLP',
  'china': 'CNY',
  'colombia': 'COP',
  'comoros': 'KMF',
  'congo (congo-brazzaville)': 'XAF',
  'costa rica': 'CRC',
  "côte d'ivoire": 'XOF',
  'croatia': 'EUR',
  'cuba': 'CUP',
  'cyprus': 'EUR',
  'czechia (czech republic)': 'CZK',
  'democratic republic of the congo': 'CDF',
  'denmark': 'DKK',
  'djibouti': 'DJF',
  'dominica': 'XCD',
  'dominican republic': 'DOP',
  'ecuador': 'USD',
  'egypt': 'EGP',
  'el salvador': 'USD',
  'equatorial guinea': 'XAF',
  'eritrea': 'ERN',
  'estonia': 'EUR',
  'eswatini (swaziland)': 'SZL',
  'ethiopia': 'ETB',
  'fiji': 'FJD',
  'finland': 'EUR',
  'france': 'EUR',
  'gabon': 'XAF',
  'gambia': 'GMD',
  'georgia': 'GEL',
  'germany': 'EUR',
  'ghana': 'GHS',
  'greece': 'EUR',
  'grenada': 'XCD',
  'guatemala': 'GTQ',
  'guinea': 'GNF',
  'guinea-bissau': 'XOF',
  'guyana': 'GYD',
  'haiti': 'HTG',
  'holy see': 'EUR',
  'honduras': 'HNL',
  'hungary': 'HUF',
  'iceland': 'ISK',
  'india': 'INR',
  'indonesia': 'IDR',
  'iran': 'IRR',
  'iraq': 'IQD',
  'ireland': 'EUR',
  'italy': 'EUR',
  'jamaica': 'JMD',
  'japan': 'JPY',
  'jordan': 'JOD',
  'kazakhstan': 'KZT',
  'kenya': 'KES',
  'kiribati': 'AUD',
  'kuwait': 'KWD',
  'kyrgyzstan': 'KGS',
  'laos': 'LAK',
  'latvia': 'EUR',
  'lebanon': 'LBP',
  'lesotho': 'LSL',
  'liberia': 'LRD',
  'libya': 'LYD',
  'liechtenstein': 'CHF',
  'lithuania': 'EUR',
  'luxembourg': 'EUR',
  'madagascar': 'MGA',
  'malawi': 'MWK',
  'malaysia': 'MYR',
  'maldives': 'MVR',
  'mali': 'XOF',
  'malta': 'EUR',
  'marshall islands': 'USD',
  'mauritania': 'MRU',
  'mauritius': 'MUR',
  'mexico': 'MXN',
  'micronesia': 'USD',
  'moldova': 'MDL',
  'monaco': 'EUR',
  'mongolia': 'MNT',
  'montenegro': 'EUR',
  'morocco': 'MAD',
  'mozambique': 'MZN',
  'myanmar (burma)': 'MMK',
  'namibia': 'NAD',
  'nauru': 'AUD',
  'nepal': 'NPR',
  'netherlands': 'EUR',
  'new zealand': 'NZD',
  'nicaragua': 'NIO',
  'niger': 'XOF',
  'nigeria': 'NGN',
  'north korea': 'KPW',
  'north macedonia': 'MKD',
  'norway': 'NOK',
  'oman': 'OMR',
  'pakistan': 'PKR',
  'palau': 'USD',
  'palestine state': 'ILS',
  'panama': 'USD',
  'papua new guinea': 'PGK',
  'paraguay': 'PYG',
  'peru': 'PEN',
  'philippines': 'PHP',
  'poland': 'PLN',
  'portugal': 'EUR',
  'qatar': 'QAR',
  'romania': 'RON',
  'russia': 'RUB',
  'rwanda': 'RWF',
  'saint kitts and nevis': 'XCD',
  'saint lucia': 'XCD',
  'saint vincent and the grenadines': 'XCD',
  'samoa': 'WST',
  'san marino': 'EUR',
  'sao tome and principe': 'STN',
  'saudi arabia': 'SAR',
  'senegal': 'XOF',
  'serbia': 'RSD',
  'seychelles': 'SCR',
  'sierra leone': 'SLE',
  'singapore': 'SGD',
  'slovakia': 'EUR',
  'slovenia': 'EUR',
  'solomon islands': 'SBD',
  'somalia': 'SOS',
  'south africa': 'ZAR',
  'south korea': 'KRW',
  'south sudan': 'SSP',
  'spain': 'EUR',
  'sri lanka': 'LKR',
  'sudan': 'SDG',
  'suriname': 'SRD',
  'sweden': 'SEK',
  'switzerland': 'CHF',
  'syria': 'SYP',
  'taiwan': 'TWD',
  'tajikistan': 'TJS',
  'tanzania': 'TZS',
  'thailand': 'THB',
  'timor-leste': 'USD',
  'togo': 'XOF',
  'tonga': 'TOP',
  'trinidad and tobago': 'TTD',
  'tunisia': 'TND',
  'turkey': 'TRY',
  'turkmenistan': 'TMT',
  'tuvalu': 'AUD',
  'uganda': 'UGX',
  'ukraine': 'UAH',
  'united arab emirates': 'AED',
  'united kingdom': 'GBP',
  'united states': 'USD',
  'uruguay': 'UYU',
  'uzbekistan': 'UZS',
  'vanuatu': 'VUV',
  'venezuela': 'VES',
  'vietnam': 'VND',
  'yemen': 'YER',
  'zambia': 'ZMW',
  'zimbabwe': 'ZWL',
};

String resolveCurrency({String? currency, String? country}) {
  final explicit = normalizeCurrencyCode(currency);
  if (explicit.isNotEmpty) return explicit;
  if (country != null && country.trim().isNotEmpty) {
    return currencyFromCountryName(country);
  }
  return kDefaultCurrency;
}

String currencySymbol(String? currency) {
  final code = resolveCurrency(currency: currency);
  return kCurrencySymbols[code] ?? code;
}

/// Formats [amount] for display in [currency] (business-local, no FX).
String formatMoney(
  num amount, {
  String? currency,
  String? freeLabel,
  bool compact = true,
}) {
  final value = amount.toDouble();
  if (value <= 0 && freeLabel != null) return freeLabel;
  final code = resolveCurrency(currency: currency);
  final symbol = currencySymbol(code);

  if (compact && value == value.roundToDouble()) {
    final whole = NumberFormat('#,##0', 'en').format(value.round());
    return '$symbol $whole';
  }

  try {
    return NumberFormat.currency(
      name: code,
      symbol: '$symbol ',
      decimalDigits: compact ? 0 : 2,
    ).format(value);
  } catch (_) {
    final formatted = NumberFormat('#,##0.##', 'en').format(value);
    return '$symbol $formatted';
  }
}

String priceFieldLabel(String? currency) {
  final code = resolveCurrency(currency: currency);
  return 'Price ($code)';
}
